# Knowledge Graph Profiling

The goal fo profiling is to produce a summary of the classes, properties and instances present in a KG. Profiling is challenging because it is comptationally expensive as the queries touch large parts of the KG. In this part of the tutorial, you will learn how to use KGTK to profile a KG, and how KGTK addresses the computatinal challenges of computing profiles. Along the way, you will learn advanced uses of the KGTK query command.

This part of the tutorial is divided into multiple subsetions:
- Counting the number of instances, classes and properties
- Counting the number of instances of each class, the the most basic form of profiling
- Extending instance counting to include the instance of all subclasses of a class
- Generalizing the Wikidata `instance of (P31)` to include `occupation (P106)` and `position held (P39)` so that our profiles include statistics about classes such as `director (P57)`, which in Wikidata don't have instances
- Counting the number of times each property is used in the instances of each class and all its subclasses; you will learn how to divide a computationally challenging task into simpler queries that you can chain together 
- Customizing the profiles to include items of interest

At the end, you will load the profile data in the browsesr so that you can get more insights into the knowledge present in the tutorial KG.

## Step 0: Install KGTK

Only run the following cell if KGTK is not installed.
 For example, if running in [Google Colab](https://colab.research.google.com/)

In [ ]:
!pip install kgtk

## Preamble: set up the environment and files used in the tutorial

In [3]:
import io
import os

from kgtk.configure_kgtk_notebooks import ConfigureKGTK
from kgtk.functions import kgtk, kypher

In [4]:
# Parameters

# Folder on local machine where to create the output and temporary folders
input_path = None
output_path = "/tmp/projects"
project_name = "tutorial-profiling"

Our Wikidata distribution partitions the knowledge in Wikidata into smaller files that make it possible for you to pick and choose which files you want to use. Our tutorial KG is a subset of Wikidata, and is partitioned in the same way as the full Wikidata. The following is a partial list of all the files:

In [5]:
files = [
    "all",
    "label",
    "quantity",
    "item",
    "wikibase_property",
    "qualifiers",
    "p279star",
    "p31"
]
ck = ConfigureKGTK(files)
ck.configure_kgtk(input_graph_path=input_path,
                  output_path=output_path,
                  project_name=project_name)

User home: /home/ktyao
Current dir: /home/ktyao/dev/kgtk-notebooks/tutorial
KGTK dir: /home/ktyao/dev/kgtk-notebooks
Use-cases dir: /home/ktyao/dev/kgtk-notebooks/use-cases
--2022-04-27 11:00:28--  https://github.com/usc-isi-i2/kgtk-tutorial-files/raw/main/datasets/arnold/all.tsv.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/all.tsv.gz [following]
--2022-04-27 11:00:29--  https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/all.tsv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/all.tsv.gz [following]
--2022-04-27 11:00:29--  https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/all.tsv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45510513 (43M) [application/octet-stream]
Saving to: ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/all.tsv.gz’

     0K .......... .......... .......... .......... ..........  0% 1.05M 41s
    50K .......... .......... .......... .......... ..........  0% 1.35M 37s
   100K .......... .......... .......... .......... ..........  0% 2.15M 31s
   150K .......... .......... .......... .......... ..........  0% 1.82M 29s
   200K .......... .......... .......... .......... ..........  0% 2.32M 27s
   250K .......... .......... .......... .......... ..........  0% 2.43M 25s
   300K .......... .......... .......... .......... ..........  0% 2.20M 25s
   350K .......... .......... .......... .......... ..........  0% 2.25M 24s
   400K .......... .......... .......... .......... ..........  1% 3.27M 23s
   450K .......... .......... .......... .......... ..........  1% 4.07M 21s
   500K .......... .......... .......... .......... ..........  1% 5.59M 20s
   550K .......... .......... .......... .......... ..........  1% 2.30M 20s
   600K .......... .......... .......... .......... ..........  1% 2.92M 20s
   650K .......... .......... .......... .......... ..........  1% 3.57M 19s
   700K .......... .......... .......... .......... ..........  1% 2.92M 19s
   750K .......... .......... .......... .......... ..........  1% 2.61M 19s
   800K .......... .......... .......... .......... ..........  1% 4.13M 18s
   850K .......... .......... .......... .......... ..........  2% 4.70M 18s
   900K .......... .......... .......... .......... ..........  2% 4.39M 17s
   950K .......... .......... .......... .......... ..........  2% 3.06M 17s
  1000K .......... .......... .......... .......... ..........  2% 3.57M 17s
  1050K .......... .......... .......... .......... ..........  2% 6.50M 16s
  1100K .......... .......... .......... .......... ..........  2% 7.10M 16s
  1150K .......... .......... .......... .......... ..........  2% 4.85M 15s
  1200K .......... .......... .......... .......... ..........  2% 10.2M 15s
  1250K .......... .......... .......... .......... ..........  2% 5.10M 15s
  1300K .......... .......... .......... .......... ..........  3% 7.29M 14s
  1350K .......... .......... .......... .......... ..........  3% 7.37M 14s
  1400K .......... .......... .......... .......... ..........  3% 6.20M 14s
  1450K .......... .......... .......... .......... ..........  3% 8.84M 13s
  1500K .......... .......... .......... .......... ..........  3% 3.83M 13s
  1550K .......... .......... .......... .......... ..........  3% 6.69M 13s
  1600K .......... .......... .......... .......... ..........  3% 4.02M 13s
  1650K .......... .......... .......... .......... ..........  3% 8.70M 13s
  1700K .......... .......... .......... .......... ..........  3% 3.90M 13s
  1750K .......... .......... .......... .......... ..........  4% 8.10M 12s
  1800K .......... .......... .......... .......... ..........  4% 8.80M 12s
  1850K .......... .......... .......... .......... ..........  4% 5.39M 12s
  1900K .......... .......... .......... .......... ..........  4% 9.60M 12s
  1950K .......... .......... .......... .......... ..........  4% 4.83M 12s
  2000K .......... .......... .......... .......... ..........  4% 9.52M 12s
  2050K .......... .......... .......... .......... ..........  4% 6.08M 11s
  2100K .......... .......... .......... .......... ..........  4% 8.09M 11s
  2150K .......... .......... .......... .......... ..........  4% 11.2M 11s
  2200K .......... .......... .......... .......... ..........  5% 5.57M 11s
  2250K .......... .......... .......... .......... ..........  5% 8.41M 11s
  2300K .......... .......... .......... .......... ..........  5% 11.6M 11s
  2350K .......... .......... .......... .......... ..........  5% 5.48M 11s
  2400K .......... .......... .......... .......... ..........  5% 11.3M 10s
  2450K .......... .......... .......... .......... ..........  5% 6.29M 10s
  2500K .......... .......... .......... .......... ..........  5% 8.60M 10s
  2550K .......... .......... .......... .......... ..........  5% 11.2M 10s
  2600K .......... .......... .......... .......... ..........  5% 5.73M 10s
  2650K .......... .......... .......... .......... ..........  6% 11.2M 10s
  2700K .......... .......... .......... .......... ..........  6% 11.6M 10s
  2750K .......... .......... .......... .......... ..........  6% 6.65M 10s
  2800K .......... .......... .......... .......... ..........  6% 11.2M 10s
  2850K .......... .......... .......... .......... ..........  6% 11.8M 9s
  2900K .......... .......... .......... .......... ..........  6% 11.4M 9s
  2950K .......... .......... .......... .......... ..........  6% 7.02M 9s
  3000K .......... .......... .......... .......... ..........  6% 10.7M 9s
  3050K .......... .......... .......... .......... ..........  6% 8.64M 9s
  3100K .......... .......... .......... .......... ..........  7% 6.55M 9s
  3150K .......... .......... .......... .......... ..........  7% 8.76M 9s
  3200K .......... .......... .......... .......... ..........  7% 11.7M 9s
  3250K .......... .......... .......... .......... ..........  7% 11.6M 9s
  3300K .......... .......... .......... .......... ..........  7% 11.4M 9s
  3350K .......... .......... .......... .......... ..........  7% 7.79M 9s
  3400K .......... .......... .......... .......... ..........  7% 11.3M 9s
  3450K .......... .......... .......... .......... ..........  7% 11.7M 8s
  3500K .......... .......... .......... .......... ..........  7% 11.0M 8s
  3550K .......... .......... .......... .......... ..........  8% 6.37M 8s
  3600K .......... .......... .......... .......... ..........  8% 11.6M 8s
  3650K .......... .......... .......... .......... ..........  8% 9.80M 8s
  3700K .......... .......... .......... .......... ..........  8% 11.7M 8s
  3750K .......... .......... .......... .......... ..........  8% 11.2M 8s
  3800K .......... .......... .......... .......... ..........  8% 11.6M 8s
  3850K .......... .......... .......... .......... ..........  8% 11.4M 8s
  3900K .......... .......... .......... .......... ..........  8% 11.7M 8s
  3950K .......... .......... .......... .......... ..........  9% 8.72M 8s
  4000K .......... .......... .......... .......... ..........  9% 11.7M 8s
  4050K .......... .......... .......... .......... ..........  9% 11.3M 8s
  4100K .......... .......... .......... .......... ..........  9% 11.7M 8s
  4150K .......... .......... .......... .......... ..........  9% 11.1M 8s
  4200K .......... .......... .......... .......... ..........  9% 11.7M 7s
  4250K .......... .......... .......... .......... ..........  9% 11.3M 7s
  4300K .......... .......... .......... .......... ..........  9% 11.7M 7s
  4350K .......... .......... .......... .......... ..........  9% 8.73M 7s
  4400K .......... .......... .......... .......... .......... 10% 11.3M 7s
  4450K .......... .......... .......... .......... .......... 10% 11.7M 7s
  4500K .......... .......... .......... .......... .......... 10% 11.3M 7s
  4550K .......... .......... .......... .......... .......... 10% 11.5M 7s
  4600K .......... .......... .......... .......... .......... 10% 11.3M 7s
  4650K .......... .......... .......... .......... .......... 10% 11.7M 7s
  4700K .......... .......... .......... .......... .......... 10% 11.7M 7s
  4750K .......... .......... .......... .......... .......... 10% 8.75M 7s
  4800K .......... .......... .......... .......... .......... 10% 11.4M 7s
  4850K .......... .......... .......... .......... .......... 11% 11.6M 7s
  4900K .......... .......... .......... .......... .......... 11% 11.4M 7s
  4950K .......... .......... .......... .......... .......... 11% 11.5M 7s
  5000K .......... .......... .......... .......... .......... 11% 11.3M 7s
  5050K .......... .......... .......... .......... .......... 11% 11.7M 7s
  5100K .......... .......... .......... .......... .......... 11% 11.4M 7s
  5150K .......... .......... .......... .......... .......... 11% 8.74M 7s
  5200K .......... .......... .......... .......... .......... 11% 11.7M 7s
  5250K .......... .......... .......... .......... .......... 11% 11.3M 7s
  5300K .......... .......... .......... .......... .......... 12% 11.7M 7s
  5350K .......... .......... .......... .......... .......... 12% 11.4M 6s
  5400K .......... .......... .......... .......... .......... 12% 11.4M 6s
  5450K .......... .......... .......... .......... .......... 12% 11.5M 6s
  5500K .......... .......... .......... .......... .......... 12% 11.4M 6s
  5550K .......... .......... .......... .......... .......... 12% 8.78M 6s
  5600K .......... .......... .......... .......... .......... 12% 11.7M 6s
  5650K .......... .......... .......... .......... .......... 12% 11.4M 6s
  5700K .......... .......... .......... .......... .......... 12% 11.7M 6s
  5750K .......... .......... .......... .......... .......... 13% 11.1M 6s
  5800K .......... .......... .......... .......... .......... 13% 11.7M 6s
  5850K .......... .......... .......... .......... .......... 13% 11.3M 6s
  5900K .......... .......... .......... .......... .......... 13% 11.7M 6s
  5950K .......... .......... .......... .......... .......... 13% 8.75M 6s
  6000K .......... .......... .......... .......... .......... 13% 11.4M 6s
  6050K .......... .......... .......... .......... .......... 13% 11.7M 6s
  6100K .......... .......... .......... .......... .......... 13% 11.6M 6s
  6150K .......... .......... .......... .......... .......... 13% 1.79M 6s
  6200K .......... .......... .......... .......... .......... 14% 30.5M 6s
  6250K .......... .......... .......... .......... .......... 14% 26.2M 6s
  6300K .......... .......... .......... .......... .......... 14% 27.6M 6s
  6350K .......... .......... .......... .......... .......... 14% 12.7M 6s
  6400K .......... .......... .......... .......... .......... 14% 50.7M 6s
  6450K .......... .......... .......... .......... .......... 14% 59.9M 6s
  6500K .......... .......... .......... .......... .......... 14% 66.2M 6s
  6550K .......... .......... .......... .......... .......... 14% 6.67M 6s
  6600K .......... .......... .......... .......... .......... 14% 11.3M 6s
  6650K .......... .......... .......... .......... .......... 15% 11.7M 6s
  6700K .......... .......... .......... .......... .......... 15% 11.5M 6s
  6750K .......... .......... .......... .......... .......... 15% 6.77M 6s
  6800K .......... .......... .......... .......... .......... 15% 11.7M 6s
  6850K .......... .......... .......... .......... .......... 15% 11.6M 6s
  6900K .......... .......... .......... .......... .......... 15% 11.4M 6s
  6950K .......... .......... .......... .......... .......... 15% 11.5M 6s
  7000K .......... .......... .......... .......... .......... 15% 11.3M 6s
  7050K .......... .......... .......... .......... .......... 15% 10.9M 6s
  7100K .......... .......... .......... .......... .......... 16% 11.3M 6s
  7150K .......... .......... .......... .......... .......... 16% 8.75M 5s
  7200K .......... .......... .......... .......... .......... 16% 11.7M 5s
  7250K .......... .......... .......... .......... .......... 16% 11.3M 5s
  7300K .......... .......... .......... .......... .......... 16% 10.9M 5s
  7350K .......... .......... .......... .......... .......... 16% 11.2M 5s
  7400K .......... .......... .......... .......... .......... 16% 10.4M 5s
  7450K .......... .......... .......... .......... .......... 16% 11.5M 5s
  7500K .......... .......... .......... .......... .......... 16% 11.6M 5s
  7550K .......... .......... .......... .......... .......... 17% 7.15M 5s
  7600K .......... .......... .......... .......... .......... 17% 11.7M 5s
  7650K .......... .......... .......... .......... .......... 17% 11.3M 5s
  7700K .......... .......... .......... .......... .......... 17% 11.7M 5s
  7750K .......... .......... .......... .......... .......... 17% 11.0M 5s
  7800K .......... .......... .......... .......... .......... 17% 11.7M 5s
  7850K .......... .......... .......... .......... .......... 17% 11.4M 5s
  7900K .......... .......... .......... .......... .......... 17% 8.54M 5s
  7950K .......... .......... .......... .......... .......... 18% 8.75M 5s
  8000K .......... .......... .......... .......... .......... 18% 11.5M 5s
  8050K .......... .......... .......... .......... .......... 18% 11.7M 5s
  8100K .......... .......... .......... .......... .......... 18% 11.3M 5s
  8150K .......... .......... .......... .......... .......... 18% 11.5M 5s
  8200K .......... .......... .......... .......... .......... 18% 11.7M 5s
  8250K .......... .......... .......... .......... .......... 18% 10.9M 5s
  8300K .......... .......... .......... .......... .......... 18% 11.8M 5s
  8350K .......... .......... .......... .......... .......... 18% 7.77M 5s
  8400K .......... .......... .......... .......... .......... 19% 11.3M 5s
  8450K .......... .......... .......... .......... .......... 19% 11.7M 5s
  8500K .......... .......... .......... .......... .......... 19% 11.4M 5s
  8550K .......... .......... .......... .......... .......... 19% 11.6M 5s
  8600K .......... .......... .......... .......... .......... 19% 10.9M 5s
  8650K .......... .......... .......... .......... .......... 19% 11.7M 5s
  8700K .......... .......... .......... .......... .......... 19% 11.5M 5s
  8750K .......... .......... .......... .......... .......... 19% 8.69M 5s
  8800K .......... .......... .......... .......... .......... 19% 9.55M 5s
  8850K .......... .......... .......... .......... .......... 20% 11.3M 5s
  8900K .......... .......... .......... .......... .......... 20% 11.7M 5s
  8950K .......... .......... .......... .......... .......... 20% 11.5M 5s
  9000K .......... .......... .......... .......... .......... 20% 11.2M 5s
  9050K .......... .......... .......... .......... .......... 20% 11.8M 5s
  9100K .......... .......... .......... .......... .......... 20% 11.3M 5s
  9150K .......... .......... .......... .......... .......... 20% 7.55M 5s
  9200K .......... .......... .......... .......... .......... 20% 11.6M 5s
  9250K .......... .......... .......... .......... .......... 20% 11.3M 5s
  9300K .......... .......... .......... .......... .......... 21% 11.8M 5s
  9350K .......... .......... .......... .......... .......... 21% 11.0M 5s
  9400K .......... .......... .......... .......... .......... 21% 11.7M 5s
  9450K .......... .......... .......... .......... .......... 21% 11.4M 5s
  9500K .......... .......... .......... .......... .......... 21% 9.86M 5s
  9550K .......... .......... .......... .......... .......... 21% 8.80M 5s
  9600K .......... .......... .......... .......... .......... 21% 11.3M 5s
  9650K .......... .......... .......... .......... .......... 21% 11.7M 5s
  9700K .......... .......... .......... .......... .......... 21% 11.7M 5s
  9750K .......... .......... .......... .......... .......... 22% 11.1M 5s
  9800K .......... .......... .......... .......... .......... 22% 9.61M 5s
  9850K .......... .......... .......... .......... .......... 22% 11.4M 5s
  9900K .......... .......... .......... .......... .......... 22% 6.40M 5s
  9950K .......... .......... .......... .......... .......... 22% 8.79M 5s
 10000K .......... .......... .......... .......... .......... 22% 11.4M 5s
 10050K .......... .......... .......... .......... .......... 22% 11.7M 5s
 10100K .......... .......... .......... .......... .......... 22% 10.7M 5s
 10150K .......... .......... .......... .......... .......... 22% 11.4M 4s
 10200K .......... .......... .......... .......... .......... 23% 11.4M 4s
 10250K .......... .......... .......... .......... .......... 23% 11.7M 4s
 10300K .......... .......... .......... .......... .......... 23% 11.3M 4s
 10350K .......... .......... .......... .......... .......... 23% 8.95M 4s
 10400K .......... .......... .......... .......... .......... 23% 11.3M 4s
 10450K .......... .......... .......... .......... .......... 23% 11.7M 4s
 10500K .......... .......... .......... .......... .......... 23% 11.3M 4s
 10550K .......... .......... .......... .......... .......... 23% 11.5M 4s
 10600K .......... .......... .......... .......... .......... 23% 11.4M 4s
 10650K .......... .......... .......... .......... .......... 24% 11.6M 4s
 10700K .......... .......... .......... .......... .......... 24% 11.3M 4s
 10750K .......... .......... .......... .......... .......... 24% 8.76M 4s
 10800K .......... .......... .......... .......... .......... 24% 11.7M 4s
 10850K .......... .......... .......... .......... .......... 24% 11.4M 4s
 10900K .......... .......... .......... .......... .......... 24% 11.6M 4s
 10950K .......... .......... .......... .......... .......... 24% 11.2M 4s
 11000K .......... .......... .......... .......... .......... 24% 11.7M 4s
 11050K .......... .......... .......... .......... .......... 24% 11.7M 4s
 11100K .......... .......... .......... .......... .......... 25% 11.4M 4s
 11150K .......... .......... .......... .......... .......... 25% 8.70M 4s
 11200K .......... .......... .......... .......... .......... 25% 11.6M 4s
 11250K .......... .......... .......... .......... .......... 25% 11.3M 4s
 11300K .......... .......... .......... .......... .......... 25% 11.7M 4s
 11350K .......... .......... .......... .......... .......... 25% 11.1M 4s
 11400K .......... .......... .......... .......... .......... 25% 11.7M 4s
 11450K .......... .......... .......... .......... .......... 25% 11.3M 4s
 11500K .......... .......... .......... .......... .......... 25% 11.7M 4s
 11550K .......... .......... .......... .......... .......... 26% 8.74M 4s
 11600K .......... .......... .......... .......... .......... 26% 11.3M 4s
 11650K .......... .......... .......... .......... .......... 26% 11.7M 4s
 11700K .......... .......... .......... .......... .......... 26% 11.4M 4s
 11750K .......... .......... .......... .......... .......... 26% 11.5M 4s
 11800K .......... .......... .......... .......... .......... 26% 11.7M 4s
 11850K .......... .......... .......... .......... .......... 26% 11.3M 4s
 11900K .......... .......... .......... .......... .......... 26% 11.7M 4s
 11950K .......... .......... .......... .......... .......... 27% 8.72M 4s
 12000K .......... .......... .......... .......... .......... 27% 11.4M 4s
 12050K .......... .......... .......... .......... .......... 27% 11.7M 4s
 12100K .......... .......... .......... .......... .......... 27% 11.3M 4s

--2022-04-27 11:00:35--  https://github.com/usc-isi-i2/kgtk-tutorial-files/raw/main/datasets/arnold/labels.en.tsv.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/labels.en.tsv.gz [following]
--2022-04-27 11:00:37--  https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/labels.en.tsv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/labels.en.tsv.gz [following]
--2022-04-27 11:00:37--  https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/labels.en.tsv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1070169 (1.0M) [application/octet-stream]
Saving to: ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/labels.en.tsv.gz’

     0K .......... .......... .......... .......... ..........  4% 1.20M 1s
    50K .......... .......... .......... .......... ..........  9% 1.89M 1s
   100K .......... .......... .......... .......... .......... 14% 1.74M 1s
   150K .......... .......... .......... .......... .......... 19% 1.91M 1s
   200K .......... .......... .......... .......... .......... 23% 2.53M 0s
   250K .......... .......... .......... .......... .......... 28% 3.03M 0s
   300K .......... .......... .......... .......... .......... 33% 2.50M 0s
   350K .......... .......... .......... .......... .......... 38% 1.59M 0s
   400K .......... .......... .......... .......... .......... 43% 2.41M 0s
   450K .......... .......... .......... .......... .......... 47% 2.51M 0s
   500K .......... .......... .......... .......... .......... 52% 2.50M 0s
   550K .......... .......... .......... .......... .......... 57% 2.09M 0s
   600K .......... .......... .......... .......... .......... 62% 2.28M 0s
   650K .......... .......... .......... .......... .......... 66% 1.94M 0s
   700K .......... .......... .......... .......... .......... 71% 3.94M 0s
   750K .......... .......... .......... .......... .......... 76% 3.10M 0s
   800K .......... .......... .......... .......... .......... 81% 2.53M 0s
   850K .......... .......... .......... .......... .......... 86% 2.68M 0s
   900K .......... .......... .......... .......... .......... 90% 2.47M 0s
   950K .......... .......... .......... .......... .......... 95% 2.67M 0s
  1000K .......... .......... .......... .......... .....     100% 2.45M=0.5s

2022-04-27 11:00:38 (2.23 MB/s) - ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/labels.en.tsv.gz’ saved [1070169/1070169]

--2022-04-27 11:00:38--  https://github.com/usc-isi-i2/kgtk-tutorial-files/raw/main/datasets/arnold/claims.quantity.tsv.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/claims.quantity.tsv.gz [following]
--2022-04-27 11:00:39--  https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/claims.quantity.tsv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/claims.quantity.tsv.gz [following]
--2022-04-27 11:00:39--  https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/claims.quantity.tsv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1936951 (1.8M) [application/octet-stream]
Saving to: ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.quantity.tsv.gz’

     0K .......... .......... .......... .......... ..........  2% 1.60M 1s
    50K .......... .......... .......... .......... ..........  5% 1.52M 1s
   100K .......... .......... .......... .......... ..........  7% 1.76M 1s
   150K .......... .......... .......... .......... .......... 10% 2.06M 1s
   200K .......... .......... .......... .......... .......... 13% 1.59M 1s
   250K .......... .......... .......... .......... .......... 15% 2.18M 1s
   300K .......... .......... .......... .......... .......... 18% 2.11M 1s
   350K .......... .......... .......... .......... .......... 21% 1.37M 1s
   400K .......... .......... .......... .......... .......... 23% 2.32M 1s
   450K .......... .......... .......... .......... .......... 26% 1.92M 1s
   500K .......... .......... .......... .......... .......... 29% 2.35M 1s
   550K .......... .......... .......... .......... .......... 31% 2.65M 1s
   600K .......... .......... .......... .......... .......... 34% 2.67M 1s
   650K .......... .......... .......... .......... .......... 37% 3.33M 1s
   700K .......... .......... .......... .......... .......... 39% 2.64M 1s
   750K .......... .......... .......... .......... .......... 42% 2.03M 1s
   800K .......... .......... .......... .......... .......... 44% 2.75M 0s
   850K .......... .......... .......... .......... .......... 47% 2.57M 0s
   900K .......... .......... .......... .......... .......... 50% 2.50M 0s
   950K .......... .......... .......... .......... .......... 52% 2.90M 0s
  1000K .......... .......... .......... .......... .......... 55% 2.93M 0s
  1050K .......... .......... .......... .......... .......... 58% 2.90M 0s
  1100K .......... .......... .......... .......... .......... 60% 2.92M 0s
  1150K .......... .......... .......... .......... .......... 63% 1.77M 0s
  1200K .......... .......... .......... .......... .......... 66% 2.42M 0s
  1250K .......... .......... .......... .......... .......... 68% 4.05M 0s
  1300K .......... .......... .......... .......... .......... 71% 2.78M 0s
  1350K .......... .......... .......... .......... .......... 74% 4.36M 0s
  1400K .......... .......... .......... .......... .......... 76% 2.97M 0s
  1450K .......... .......... .......... .......... .......... 79% 2.85M 0s
  1500K .......... .......... .......... .......... .......... 81% 2.63M 0s
  1550K .......... .......... .......... .......... .......... 84% 2.74M 0s
  1600K .......... .......... .......... .......... .......... 87% 2.81M 0s
  1650K .......... .......... .......... .......... .......... 89% 4.22M 0s
  1700K .......... .......... .......... .......... .......... 92% 3.11M 0s
  1750K .......... .......... .......... .......... .......... 95% 3.21M 0s
  1800K .......... .......... .......... .......... .......... 97% 4.67M 0s
  1850K .......... .......... .......... .......... .         100% 3.14M=0.8s

2022-04-27 11:00:40 (2.46 MB/s) - ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.quantity.tsv.gz’ saved [1936951/1936951]

--2022-04-27 11:00:40--  https://github.com/usc-isi-i2/kgtk-tutorial-files/raw/main/datasets/arnold/claims.wikibase-item.tsv.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/claims.wikibase-item.tsv.gz [following]
--2022-04-27 11:00:41--  https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/claims.wikibase-item.tsv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/claims.wikibase-item.tsv.gz [following]
--2022-04-27 11:00:41--  https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/claims.wikibase-item.tsv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6342403 (6.0M) [application/octet-stream]
Saving to: ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.wikibase-item.tsv.gz’

     0K .......... .......... .......... .......... ..........  0% 3.05M 2s
    50K .......... .......... .......... .......... ..........  1% 6.42M 1s
   100K .......... .......... .......... .......... ..........  2% 3.66M 1s
   150K .......... .......... .......... .......... ..........  3% 9.44M 1s
   200K .......... .......... .......... .......... ..........  4% 5.73M 1s
   250K .......... .......... .......... .......... ..........  4% 6.93M 1s
   300K .......... .......... .......... .......... ..........  5% 3.94M 1s
   350K .......... .......... .......... .......... ..........  6% 5.04M 1s
   400K .......... .......... .......... .......... ..........  7% 8.18M 1s
   450K .......... .......... .......... .......... ..........  8% 7.62M 1s
   500K .......... .......... .......... .......... ..........  8% 4.98M 1s
   550K .......... .......... .......... .......... ..........  9% 6.85M 1s
   600K .......... .......... .......... .......... .......... 10% 8.75M 1s
   650K .......... .......... .......... .......... .......... 11% 4.73M 1s
   700K .......... .......... .......... .......... .......... 12% 10.1M 1s
   750K .......... .......... .......... .......... .......... 12% 6.23M 1s
   800K .......... .......... .......... .......... .......... 13% 4.78M 1s
   850K .......... .......... .......... .......... .......... 14% 9.44M 1s
   900K .......... .......... .......... .......... .......... 15% 8.03M 1s
   950K .......... .......... .......... .......... .......... 16% 6.47M 1s
  1000K .......... .......... .......... .......... .......... 16% 11.3M 1s
  1050K .......... .......... .......... .......... .......... 17% 8.79M 1s
  1100K .......... .......... .......... .......... .......... 18% 6.06M 1s
  1150K .......... .......... .......... .......... .......... 19% 8.42M 1s
  1200K .......... .......... .......... .......... .......... 20% 8.97M 1s
  1250K .......... .......... .......... .......... .......... 20% 6.95M 1s
  1300K .......... .......... .......... .......... .......... 21% 11.7M 1s
  1350K .......... .......... .......... .......... .......... 22% 6.15M 1s
  1400K .......... .......... .......... .......... .......... 23% 11.8M 1s
  1450K .......... .......... .......... .......... .......... 24% 9.72M 1s
  1500K .......... .......... .......... .......... .......... 25% 7.96M 1s
  1550K .......... .......... .......... .......... .......... 25% 6.22M 1s
  1600K .......... .......... .......... .......... .......... 26% 11.6M 1s
  1650K .......... .......... .......... .......... .......... 27% 8.27M 1s
  1700K .......... .......... .......... .......... .......... 28% 7.60M 1s
  1750K .......... .......... .......... .......... .......... 29% 10.1M 1s
  1800K .......... .......... .......... .......... .......... 29% 11.7M 1s
  1850K .......... .......... .......... .......... .......... 30% 11.4M 1s
  1900K .......... .......... .......... .......... .......... 31% 11.6M 1s
  1950K .......... .......... .......... .......... .......... 32% 6.28M 1s
  2000K .......... .......... .......... .......... .......... 33% 11.4M 1s
  2050K .......... .......... .......... .......... .......... 33% 11.7M 1s
  2100K .......... .......... .......... .......... .......... 34% 7.82M 1s
  2150K .......... .......... .......... .......... .......... 35% 11.6M 1s
  2200K .......... .......... .......... .......... .......... 36% 11.7M 1s
  2250K .......... .......... .......... .......... .......... 37% 8.48M 1s
  2300K .......... .......... .......... .......... .......... 37% 8.08M 1s
  2350K .......... .......... .......... .......... .......... 38% 8.68M 1s
  2400K .......... .......... .......... .......... .......... 39% 11.3M 0s
  2450K .......... .......... .......... .......... .......... 40% 11.7M 0s
  2500K .......... .......... .......... .......... .......... 41% 11.3M 0s
  2550K .......... .......... .......... .......... .......... 41% 11.0M 0s
  2600K .......... .......... .......... .......... .......... 42% 11.3M 0s
  2650K .......... .......... .......... .......... .......... 43% 11.7M 0s
  2700K .......... .......... .......... .......... .......... 44% 11.3M 0s
  2750K .......... .......... .......... .......... .......... 45% 8.68M 0s
  2800K .......... .......... .......... .......... .......... 46% 11.8M 0s
  2850K .......... .......... .......... .......... .......... 46% 9.24M 0s
  2900K .......... .......... .......... .......... .......... 47% 9.33M 0s
  2950K .......... .......... .......... .......... .......... 48% 11.5M 0s
  3000K .......... .......... .......... .......... .......... 49% 11.3M 0s
  3050K .......... .......... .......... .......... .......... 50% 11.7M 0s
  3100K .......... .......... .......... .......... .......... 50% 11.5M 0s
  3150K .......... .......... .......... .......... .......... 51% 8.65M 0s
  3200K .......... .......... .......... .......... .......... 52% 11.6M 0s
  3250K .......... .......... .......... .......... .......... 53% 11.4M 0s
  3300K .......... .......... .......... .......... .......... 54% 11.7M 0s
  3350K .......... .......... .......... .......... .......... 54% 11.3M 0s
  3400K .......... .......... .......... .......... .......... 55% 11.5M 0s
  3450K .......... .......... .......... .......... .......... 56% 11.4M 0s
  3500K .......... .......... .......... .......... .......... 57% 11.6M 0s
  3550K .......... .......... .......... .......... .......... 58% 8.71M 0s
  3600K .......... .......... .......... .......... .......... 58% 11.6M 0s
  3650K .......... .......... .......... .......... .......... 59% 11.4M 0s
  3700K .......... .......... .......... .......... .......... 60% 11.8M 0s
  3750K .......... .......... .......... .......... .......... 61% 11.2M 0s
  3800K .......... .......... .......... .......... .......... 62% 11.7M 0s
  3850K .......... .......... .......... .......... .......... 62% 11.4M 0s
  3900K .......... .......... .......... .......... .......... 63% 11.6M 0s
  3950K .......... .......... .......... .......... .......... 64% 8.69M 0s
  4000K .......... .......... .......... .......... .......... 65% 11.3M 0s
  4050K .......... .......... .......... .......... .......... 66% 11.7M 0s
  4100K .......... .......... .......... .......... .......... 67% 11.3M 0s
  4150K .......... .......... .......... .......... .......... 67% 11.5M 0s
  4200K .......... .......... .......... .......... .......... 68% 11.3M 0s
  4250K .......... .......... .......... .......... .......... 69% 11.5M 0s
  4300K .......... .......... .......... .......... .......... 70% 11.8M 0s
  4350K .......... .......... .......... .......... .......... 71% 8.75M 0s
  4400K .......... .......... .......... .......... .......... 71% 11.4M 0s
  4450K .......... .......... .......... .......... .......... 72% 11.6M 0s
  4500K .......... .......... .......... .......... .......... 73% 11.4M 0s
  4550K .......... .......... .......... .......... .......... 74% 11.4M 0s
  4600K .......... .......... .......... .......... .......... 75% 11.3M 0s
  4650K .......... .......... .......... .......... .......... 75% 2.06M 0s
  4700K .......... .......... .......... .......... .......... 76% 24.8M 0s
  4750K .......... .......... .......... .......... .......... 77% 14.1M 0s
  4800K .......... .......... .......... .......... .......... 78% 15.4M 0s
  4850K .......... .......... .......... .......... .......... 79% 26.6M 0s
  4900K .......... .......... .......... .......... .......... 79%  112M 0s
  4950K .......... .......... .......... .......... .......... 80%  115M 0s
  5000K .......... .......... .......... .......... .......... 81% 11.6M 0s
  5050K .......... .......... .......... .......... .......... 82% 11.7M 0s
  5100K .......... .......... .......... .......... .......... 83% 11.1M 0s
  5150K .......... .......... .......... .......... .......... 83% 8.83M 0s
  5200K .......... .......... .......... .......... .......... 84% 11.7M 0s
  5250K .......... .......... .......... .......... .......... 85% 11.4M 0s
  5300K .......... .......... .......... .......... .......... 86% 11.6M 0s
  5350K .......... .......... .......... .......... .......... 87% 11.1M 0s
  5400K .......... .......... .......... .......... .......... 87% 11.7M 0s
  5450K .......... .......... .......... .......... .......... 88% 11.3M 0s
  5500K .......... .......... .......... .......... .......... 89% 11.8M 0s
  5550K .......... .......... .......... .......... .......... 90% 8.69M 0s
  5600K .......... .......... .......... .......... .......... 91% 11.3M 0s
  5650K .......... .......... .......... .......... .......... 92% 11.7M 0s
  5700K .......... .......... .......... .......... .......... 92% 10.1M 0s
  5750K .......... .......... .......... .......... .......... 93% 11.6M 0s
  5800K .......... .......... .......... .......... .......... 94% 11.6M 0s
  5850K .......... .......... .......... .......... .......... 95% 11.3M 0s
  5900K .......... .......... .......... .......... .......... 96% 11.7M 0s
  5950K .......... .......... .......... .......... .......... 96% 8.36M 0s
  6000K .......... .......... .......... .......... .......... 97% 11.4M 0s
  6050K .......... .......... .......... .......... .......... 98% 11.6M 0s
  6100K .......... .......... .......... .......... .......... 99% 11.3M 0s
  6150K .......... .......... .......... .......... ...       100% 14.5M=0.7s

2022-04-27 11:00:42 (9.15 MB/s) - ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.wikibase-item.tsv.gz’ saved [6342403/6342403]

--2022-04-27 11:00:42--  https://github.com/usc-isi-i2/kgtk-tutorial-files/raw/main/datasets/arnold/claims.wikibase-property.tsv.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/claims.wikibase-property.tsv.gz [following]
--2022-04-27 11:00:43--  https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/claims.wikibase-property.tsv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/claims.wikibase-property.tsv.gz [following]
--2022-04-27 11:00:43--  https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/claims.wikibase-property.tsv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 99436 (97K) [application/octet-stream]
Saving to: ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.wikibase-property.tsv.gz’

     0K .......... .......... .......... .......... .......... 51% 2.65M 0s
    50K .......... .......... .......... .......... .......   100% 9.15M=0.02s

2022-04-27 11:00:43 (4.04 MB/s) - ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.wikibase-property.tsv.gz’ saved [99436/99436]

--2022-04-27 11:00:44--  https://github.com/usc-isi-i2/kgtk-tutorial-files/raw/main/datasets/arnold/qualifiers.tsv.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/qualifiers.tsv.gz [following]
--2022-04-27 11:00:44--  https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/qualifiers.tsv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/qualifiers.tsv.gz [following]
--2022-04-27 11:00:45--  https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/qualifiers.tsv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6244298 (6.0M) [application/octet-stream]
Saving to: ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/qualifiers.tsv.gz’

     0K .......... .......... .......... .......... ..........  0% 2.26M 3s
    50K .......... .......... .......... .......... ..........  1% 4.81M 2s
   100K .......... .......... .......... .......... ..........  2% 3.91M 2s
   150K .......... .......... .......... .......... ..........  3% 3.30M 2s
   200K .......... .......... .......... .......... ..........  4% 5.89M 2s
   250K .......... .......... .......... .......... ..........  4% 4.69M 2s
   300K .......... .......... .......... .......... ..........  5% 3.25M 2s
   350K .......... .......... .......... .......... ..........  6% 3.26M 2s
   400K .......... .......... .......... .......... ..........  7% 6.99M 1s
   450K .......... .......... .......... .......... ..........  8% 4.17M 1s
   500K .......... .......... .......... .......... ..........  9% 5.70M 1s
   550K .......... .......... .......... .......... ..........  9% 3.33M 1s
   600K .......... .......... .......... .......... .......... 10% 5.00M 1s
   650K .......... .......... .......... .......... .......... 11% 6.81M 1s
   700K .......... .......... .......... .......... .......... 12% 4.64M 1s
   750K .......... .......... .......... .......... .......... 13% 4.75M 1s
   800K .......... .......... .......... .......... .......... 13% 6.41M 1s
   850K .......... .......... .......... .......... .......... 14% 4.54M 1s
   900K .......... .......... .......... .......... .......... 15% 8.01M 1s
   950K .......... .......... .......... .......... .......... 16% 4.04M 1s
  1000K .......... .......... .......... .......... .......... 17% 8.76M 1s
  1050K .......... .......... .......... .......... .......... 18% 3.94M 1s
  1100K .......... .......... .......... .......... .......... 18% 9.15M 1s
  1150K .......... .......... .......... .......... .......... 19% 4.21M 1s
  1200K .......... .......... .......... .......... .......... 20% 9.89M 1s
  1250K .......... .......... .......... .......... .......... 21% 10.7M 1s
  1300K .......... .......... .......... .......... .......... 22% 4.29M 1s
  1350K .......... .......... .......... .......... .......... 22% 11.4M 1s
  1400K .......... .......... .......... .......... .......... 23% 8.29M 1s
  1450K .......... .......... .......... .......... .......... 24% 4.37M 1s
  1500K .......... .......... .......... .......... .......... 25% 9.55M 1s
  1550K .......... .......... .......... .......... .......... 26% 5.42M 1s
  1600K .......... .......... .......... .......... .......... 27% 11.4M 1s
  1650K .......... .......... .......... .......... .......... 27% 11.7M 1s
  1700K .......... .......... .......... .......... .......... 28% 6.12M 1s
  1750K .......... .......... .......... .......... .......... 29% 6.32M 1s
  1800K .......... .......... .......... .......... .......... 30% 11.3M 1s
  1850K .......... .......... .......... .......... .......... 31% 11.1M 1s
  1900K .......... .......... .......... .......... .......... 31% 11.3M 1s
  1950K .......... .......... .......... .......... .......... 32% 3.71M 1s
  2000K .......... .......... .......... .......... .......... 33% 11.7M 1s
  2050K .......... .......... .......... .......... .......... 34% 11.3M 1s
  2100K .......... .......... .......... .......... .......... 35% 7.08M 1s
  2150K .......... .......... .......... .......... .......... 36% 7.69M 1s
  2200K .......... .......... .......... .......... .......... 36% 11.6M 1s
  2250K .......... .......... .......... .......... .......... 37% 11.4M 1s
  2300K .......... .......... .......... .......... .......... 38% 11.6M 1s
  2350K .......... .......... .......... .......... .......... 39% 8.67M 1s
  2400K .......... .......... .......... .......... .......... 40% 8.31M 1s
  2450K .......... .......... .......... .......... .......... 40% 9.66M 1s
  2500K .......... .......... .......... .......... .......... 41% 11.7M 1s
  2550K .......... .......... .......... .......... .......... 42% 11.2M 1s
  2600K .......... .......... .......... .......... .......... 43% 7.26M 1s
  2650K .......... .......... .......... .......... .......... 44% 8.62M 1s
  2700K .......... .......... .......... .......... .......... 45% 11.7M 1s
  2750K .......... .......... .......... .......... .......... 45% 7.84M 1s
  2800K .......... .......... .......... .......... .......... 46% 8.84M 1s
  2850K .......... .......... .......... .......... .......... 47% 11.7M 1s
  2900K .......... .......... .......... .......... .......... 48% 10.2M 0s
  2950K .......... .......... .......... .......... .......... 49% 11.5M 0s
  3000K .......... .......... .......... .......... .......... 50% 11.7M 0s
  3050K .......... .......... .......... .......... .......... 50% 11.3M 0s
  3100K .......... .......... .......... .......... .......... 51% 11.7M 0s
  3150K .......... .......... .......... .......... .......... 52% 8.69M 0s
  3200K .......... .......... .......... .......... .......... 53% 11.4M 0s
  3250K .......... .......... .......... .......... .......... 54% 7.77M 0s
  3300K .......... .......... .......... .......... .......... 54% 11.3M 0s
  3350K .......... .......... .......... .......... .......... 55% 11.6M 0s
  3400K .......... .......... .......... .......... .......... 56% 11.4M 0s
  3450K .......... .......... .......... .......... .......... 57% 11.6M 0s
  3500K .......... .......... .......... .......... .......... 58% 11.3M 0s
  3550K .......... .......... .......... .......... .......... 59% 8.69M 0s
  3600K .......... .......... .......... .......... .......... 59% 11.7M 0s
  3650K .......... .......... .......... .......... .......... 60% 11.4M 0s
  3700K .......... .......... .......... .......... .......... 61% 11.7M 0s
  3750K .......... .......... .......... .......... .......... 62% 11.5M 0s
  3800K .......... .......... .......... .......... .......... 63% 11.5M 0s
  3850K .......... .......... .......... .......... .......... 63% 11.6M 0s
  3900K .......... .......... .......... .......... .......... 64% 11.3M 0s
  3950K .......... .......... .......... .......... .......... 65% 8.69M 0s
  4000K .......... .......... .......... .......... .......... 66% 11.7M 0s
  4050K .......... .......... .......... .......... .......... 67% 11.4M 0s
  4100K .......... .......... .......... .......... .......... 68% 11.6M 0s
  4150K .......... .......... .......... .......... .......... 68% 11.3M 0s
  4200K .......... .......... .......... .......... .......... 69% 11.7M 0s
  4250K .......... .......... .......... .......... .......... 70% 11.3M 0s
  4300K .......... .......... .......... .......... .......... 71% 11.6M 0s
  4350K .......... .......... .......... .......... .......... 72% 8.67M 0s
  4400K .......... .......... .......... .......... .......... 72% 11.7M 0s
  4450K .......... .......... .......... .......... .......... 73% 11.3M 0s
  4500K .......... .......... .......... .......... .......... 74% 11.7M 0s
  4550K .......... .......... .......... .......... .......... 75% 11.2M 0s
  4600K .......... .......... .......... .......... .......... 76% 11.7M 0s
  4650K .......... .......... .......... .......... .......... 77% 11.2M 0s
  4700K .......... .......... .......... .......... .......... 77% 11.8M 0s
  4750K .......... .......... .......... .......... .......... 78% 8.73M 0s
  4800K .......... .......... .......... .......... .......... 79% 11.3M 0s
  4850K .......... .......... .......... .......... .......... 80% 11.7M 0s
  4900K .......... .......... .......... .......... .......... 81% 11.4M 0s
  4950K .......... .......... .......... .......... .......... 81% 11.5M 0s
  5000K .......... .......... .......... .......... .......... 82% 11.3M 0s
  5050K .......... .......... .......... .......... .......... 83% 11.7M 0s
  5100K .......... .......... .......... .......... .......... 84% 11.4M 0s
  5150K .......... .......... .......... .......... .......... 85% 8.94M 0s
  5200K .......... .......... .......... .......... .......... 86% 11.4M 0s
  5250K .......... .......... .......... .......... .......... 86% 11.6M 0s
  5300K .......... .......... .......... .......... .......... 87% 11.3M 0s
  5350K .......... .......... .......... .......... .......... 88% 1.77M 0s
  5400K .......... .......... .......... .......... .......... 89%  174M 0s
  5450K .......... .......... .......... .......... .......... 90%  173M 0s
  5500K .......... .......... .......... .......... .......... 91%  160M 0s
  5550K .......... .......... .......... .......... .......... 91%  140M 0s
  5600K .......... .......... .......... .......... .......... 92%  172M 0s
  5650K .......... .......... .......... .......... .......... 93% 23.5M 0s
  5700K .......... .......... .......... .......... .......... 94% 11.8M 0s
  5750K .......... .......... .......... .......... .......... 95% 8.24M 0s
  5800K .......... .......... .......... .......... .......... 95% 5.97M 0s
  5850K .......... .......... .......... .......... .......... 96% 11.6M 0s
  5900K .......... .......... .......... .......... .......... 97% 11.3M 0s
  5950K .......... .......... .......... .......... .......... 98% 8.71M 0s
  6000K .......... .......... .......... .......... .......... 99% 8.70M 0s
  6050K .......... .......... .......... .......... .......   100% 15.1M=0.7s

2022-04-27 11:00:46 (7.95 MB/s) - ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/qualifiers.tsv.gz’ saved [6244298/6244298]

--2022-04-27 11:00:46--  https://github.com/usc-isi-i2/kgtk-tutorial-files/raw/main/datasets/arnold/derived.P279star.tsv.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/derived.P279star.tsv.gz [following]
--2022-04-27 11:00:47--  https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/derived.P279star.tsv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/derived.P279star.tsv.gz [following]
--2022-04-27 11:00:47--  https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/derived.P279star.tsv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3351678 (3.2M) [application/octet-stream]
Saving to: ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/derived.P279star.tsv.gz’

     0K .......... .......... .......... .......... ..........  1% 1.58M 2s
    50K .......... .......... .......... .......... ..........  3% 1.36M 2s
   100K .......... .......... .......... .......... ..........  4% 2.08M 2s
   150K .......... .......... .......... .......... ..........  6% 2.10M 2s
   200K .......... .......... .......... .......... ..........  7% 1.73M 2s
   250K .......... .......... .......... .......... ..........  9% 2.16M 2s
   300K .......... .......... .......... .......... .......... 10% 1.94M 2s
   350K .......... .......... .......... .......... .......... 12% 1.46M 2s
   400K .......... .......... .......... .......... .......... 13% 2.30M 2s
   450K .......... .......... .......... .......... .......... 15% 2.19M 1s
   500K .......... .......... .......... .......... .......... 16% 2.33M 1s
   550K .......... .......... .......... .......... .......... 18% 2.14M 1s
   600K .......... .......... .......... .......... .......... 19% 2.36M 1s
   650K .......... .......... .......... .......... .......... 21% 3.02M 1s
   700K .......... .......... .......... .......... .......... 22% 3.30M 1s
   750K .......... .......... .......... .......... .......... 24% 2.11M 1s
   800K .......... .......... .......... .......... .......... 25% 2.44M 1s
   850K .......... .......... .......... .......... .......... 27% 2.29M 1s
   900K .......... .......... .......... .......... .......... 29% 2.92M 1s
   950K .......... .......... .......... .......... .......... 30% 2.63M 1s
  1000K .......... .......... .......... .......... .......... 32% 2.49M 1s
  1050K .......... .......... .......... .......... .......... 33% 2.55M 1s
  1100K .......... .......... .......... .......... .......... 35% 2.72M 1s
  1150K .......... .......... .......... .......... .......... 36% 2.34M 1s
  1200K .......... .......... .......... .......... .......... 38% 2.67M 1s
  1250K .......... .......... .......... .......... .......... 39% 4.39M 1s
  1300K .......... .......... .......... .......... .......... 41% 3.34M 1s
  1350K .......... .......... .......... .......... .......... 42% 2.68M 1s
  1400K .......... .......... .......... .......... .......... 44% 3.33M 1s
  1450K .......... .......... .......... .......... .......... 45% 3.45M 1s
  1500K .......... .......... .......... .......... .......... 47% 2.86M 1s
  1550K .......... .......... .......... .......... .......... 48% 2.32M 1s
  1600K .......... .......... .......... .......... .......... 50% 4.15M 1s
  1650K .......... .......... .......... .......... .......... 51% 3.28M 1s
  1700K .......... .......... .......... .......... .......... 53% 3.24M 1s
  1750K .......... .......... .......... .......... .......... 54% 3.01M 1s
  1800K .......... .......... .......... .......... .......... 56% 4.26M 1s
  1850K .......... .......... .......... .......... .......... 58% 3.49M 1s
  1900K .......... .......... .......... .......... .......... 59% 2.98M 1s
  1950K .......... .......... .......... .......... .......... 61% 2.69M 1s
  2000K .......... .......... .......... .......... .......... 62% 2.97M 0s
  2050K .......... .......... .......... .......... .......... 64% 3.70M 0s
  2100K .......... .......... .......... .......... .......... 65% 3.62M 0s
  2150K .......... .......... .......... .......... .......... 67% 4.66M 0s
  2200K .......... .......... .......... .......... .......... 68% 3.89M 0s
  2250K .......... .......... .......... .......... .......... 70% 5.77M 0s
  2300K .......... .......... .......... .......... .......... 71% 3.18M 0s
  2350K .......... .......... .......... .......... .......... 73% 2.65M 0s
  2400K .......... .......... .......... .......... .......... 74% 2.82M 0s
  2450K .......... .......... .......... .......... .......... 76% 3.27M 0s
  2500K .......... .......... .......... .......... .......... 77% 4.56M 0s
  2550K .......... .......... .......... .......... .......... 79% 3.94M 0s
  2600K .......... .......... .......... .......... .......... 80% 4.85M 0s
  2650K .......... .......... .......... .......... .......... 82% 3.65M 0s
  2700K .......... .......... .......... .......... .......... 84% 3.66M 0s
  2750K .......... .......... .......... .......... .......... 85% 2.81M 0s
  2800K .......... .......... .......... .......... .......... 87% 5.71M 0s
  2850K .......... .......... .......... .......... .......... 88% 5.11M 0s
  2900K .......... .......... .......... .......... .......... 90% 7.06M 0s
  2950K .......... .......... .......... .......... .......... 91% 3.33M 0s
  3000K .......... .......... .......... .......... .......... 93% 5.58M 0s
  3050K .......... .......... .......... .......... .......... 94% 4.40M 0s
  3100K .......... .......... .......... .......... .......... 96% 3.05M 0s
  3150K .......... .......... .......... .......... .......... 97% 3.93M 0s
  3200K .......... .......... .......... .......... .......... 99% 4.24M 0s
  3250K .......... .......... ...                             100% 17.3M=1.1s

2022-04-27 11:00:49 (2.89 MB/s) - ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/derived.P279star.tsv.gz’ saved [3351678/3351678]

--2022-04-27 11:00:49--  https://github.com/usc-isi-i2/kgtk-tutorial-files/raw/main/datasets/arnold/derived.P31.tsv.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/derived.P31.tsv.gz [following]
--2022-04-27 11:00:49--  https://github.com/usc-isi-i2/kgtk-notebooks/raw/main/datasets/arnold/derived.P31.tsv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/derived.P31.tsv.gz [following]
--2022-04-27 11:00:50--  https://raw.githubusercontent.com/usc-isi-i2/kgtk-notebooks/main/datasets/arnold/derived.P31.tsv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1188375 (1.1M) [application/octet-stream]
Saving to: ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/derived.P31.tsv.gz’

     0K .......... .......... .......... .......... ..........  4% 2.37M 0s
    50K .......... .......... .......... .......... ..........  8% 1.98M 0s
   100K .......... .......... .......... .......... .......... 12% 1.59M 1s
   150K .......... .......... .......... .......... .......... 17% 1.98M 0s
   200K .......... .......... .......... .......... .......... 21% 1.87M 0s
   250K .......... .......... .......... .......... .......... 25% 1.75M 0s
   300K .......... .......... .......... .......... .......... 30% 2.20M 0s
   350K .......... .......... .......... .......... .......... 34% 1.64M 0s
   400K .......... .......... .......... .......... .......... 38% 2.40M 0s
   450K .......... .......... .......... .......... .......... 43% 1.94M 0s
   500K .......... .......... .......... .......... .......... 47% 2.34M 0s
   550K .......... .......... .......... .......... .......... 51% 2.45M 0s
   600K .......... .......... .......... .......... .......... 56% 2.17M 0s
   650K .......... .......... .......... .......... .......... 60% 2.32M 0s
   700K .......... .......... .......... .......... .......... 64% 2.21M 0s
   750K .......... .......... .......... .......... .......... 68% 2.25M 0s
   800K .......... .......... .......... .......... .......... 73% 2.93M 0s
   850K .......... .......... .......... .......... .......... 77% 2.12M 0s
   900K .......... .......... .......... .......... .......... 81% 3.01M 0s
   950K .......... .......... .......... .......... .......... 86% 2.87M 0s
  1000K .......... .......... .......... .......... .......... 90% 2.47M 0s
  1050K .......... .......... .......... .......... .......... 94% 3.17M 0s
  1100K .......... .......... .......... .......... .......... 99% 3.33M 0s
  1150K ..........                                            100% 2.32M=0.5s

2022-04-27 11:00:50 (2.23 MB/s) - ‘/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/derived.P31.tsv.gz’ saved [1188375/1188375]

The KGTK setup command defines environment variables for all the files so that you can reuse the Jupyter notebook when you install it on your local machine.

In [6]:
ck.print_env_variables()

kgtk: kgtk
GRAPH: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input
TEMP: /tmp/projects/tutorial-profiling/temp.tutorial-profiling
kypher: kgtk query --graph-cache /tmp/projects/tutorial-profiling/temp.tutorial-profiling/wikidata.sqlite3.db
STORE: /tmp/projects/tutorial-profiling/temp.tutorial-profiling/wikidata.sqlite3.db
USE_CASES_DIR: /home/ktyao/dev/kgtk-notebooks/use-cases
KGTK_GRAPH_CACHE: /tmp/projects/tutorial-profiling/temp.tutorial-profiling/wikidata.sqlite3.db
KGTK_LABEL_FILE: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/labels.en.tsv.gz
KGTK_OPTION_DEBUG: false
EXAMPLES_DIR: /home/ktyao/dev/kgtk-notebooks/examples
OUT: /tmp/projects/tutorial-profiling
all: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/all.tsv.gz
label: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/labels.en.tsv.gz
quantity: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.quantity.tsv.gz
item: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.wikibase-item.tsv.gz
wikibase_property: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.wikibase-property.tsv.gz
qualifiers: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/qualifiers.tsv.gz
p279star: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/derived.P279star.tsv.gz
p31: /home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/derived.P31.tsv.gz

The KGTK query command (https://kgtk.readthedocs.io/en/latest/transform/query/) uses a database to cache the file used in the queries. In this tutorial, we will populate the cache now to include the files we need so that later. KGTK will populate the cache on demand, the first time you use a file. I like to do it at configuration time to keep all the aliases in one place so that I can quickly come here and see the aliases of all the files.

In [7]:
%%time
ck.load_files_into_cache()

kgtk query --graph-cache /tmp/projects/tutorial-profiling/temp.tutorial-profiling/wikidata.sqlite3.db -i "/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/all.tsv.gz" --as all  -i "/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/labels.en.tsv.gz" --as label  -i "/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.quantity.tsv.gz" --as quantity  -i "/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.wikibase-item.tsv.gz" --as item  -i "/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/claims.wikibase-property.tsv.gz" --as wikibase_property  -i "/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/qualifiers.tsv.gz" --as qualifiers  -i "/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/derived.P279star.tsv.gz" --as p279star  -i "/home/ktyao/isi-kgtk-tutorial/tutorial-profiling_input/derived.P31.tsv.gz" --as p31  --limit 3
node1	label	node2	id	node2;wikidatatype
P10	alias	'gif'@en	P10-alias-en-282226-0
P10	alias	'animation'@en	P10-alias-en-2f86d8-0
P10	alias	'media'@en	P10-alias-en-c1427e-0
CPU times: user 752 µs, sys: 13.2 ms, total: 13.9 ms
Wall time: 17.5 s

## Compute global KG statistics
In this part of the tutorial we will compute global statistics about the number of instances in the KG, the number of properties used to describe all the instances and classes, and the number of classes.

Total number of edges in our graph:

In [7]:
%%bash
zcat < $all | wc -l

 2654671

Counting the total number of nodes is a bit harder as nodes can appear in the `node1` poistion or the `node2` position. 
In the queries below we count literals as nodes, as in KGTK they are nodes:
- list all the nodes that appear in the `node1` position.
- list all the nodes that appear in the `node1` position.
- concatenate and deduplicate the two files

In [8]:
kgtk("""
    query -i all
        --match '(n1)-[id]->(n2)'
        --return 'distinct n1 as id'
        -o $TEMP/node1.tsv
""")

kgtk("""
    query -i all
        --match '(n1)-[id]->(n2)'
        --return 'distinct n2 as id'
        -o $TEMP/node2.tsv
""")

kgtk("""
    cat -i $TEMP/node1.tsv -i  $TEMP/node2.tsv
    / compact
""")

                                                        id
0          $a United States. $b Department of the Interior
1        ((0?[1-9]|[1-2][0-9]|3[0-6])[LRC]?)(/(0?[1-9]|...
2        (([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]?|25[0...
3                                                  (+20) 2
4                                                  (+32) 2
...                                                    ...
1420765                                                url
1420766                                      wikibase-form
1420767                                      wikibase-item
1420768                                  wikibase-property
1420769                                     wikibase-sense

[1420770 rows x 1 columns]

Counting the number of instances is easy as we can use the `instance of (P31)` property to identify the instances:

In [9]:
%%time
kgtk("""
    query -i all
        --match '(instance)-[:P31]->(class)'
        --return 'count(distinct instance) as count_instances'
""")

CPU times: user 6.37 ms, sys: 17.7 ms, total: 24.1 ms
Wall time: 3 s

   count_instances
0            58831

Counting the number of properties used is also easy: you do a query over all statements in the KG, and count the occurrence of each property:

In [10]:
%%time
kgtk("""
    query -i all
        --match '(instance)-[l {label: property}]->(class)'
        --return 'count(distinct property) as count_property'
""")

CPU times: user 6.17 ms, sys: 14.8 ms, total: 21 ms
Wall time: 857 ms

   count_property
0            3874

Counting the number of classes is more challenging because the notion of class in Wikidata is implicit. Here, we define **class** to be any item that is involved in a `subclass of (P279)`. Some classes don't have instances, so we cannot use `instance of (P31)` to count classes. The KGTK `p279star` graph is very handy for this task, and for any other task where you want to quickly traverse the `subclass of (P279)`. KGTK defines the `subclass of (transitive) (P279star)` property to record all the superclesses of each class, includng itself.

You can count the number of classes by counting the number of distinct classes that appear as values of `P279star` :

In [11]:
%%time
kgtk("""
    query -i p279star
        --match '(class)-[:P279star]->(super_class)'
        --return 'count(distinct super_class) as count_classes'
""")

CPU times: user 5.72 ms, sys: 15.5 ms, total: 21.2 ms
Wall time: 1.28 s

   count_classes
0          14598

Count the number of qualifiers. All the qualifiers are in a file, so we can count them by getting the number of lines in the file:

In [12]:
%%bash
zcat < $qualifiers | wc -l

  322505

You can also count the number of qualifier edges using a query, and it is instructive to do it as tis example shows how to access the qualifiers on an edge:
- The first match clasuse has `[id]`, which binds the variable `id` to the identifier of the edge.
- The second match clause uses `(id)` in the `node1` position, and puts the identifier of the qualifier edge in the `qualifier_id` variable.
- The retrun statement returns the count of `qualifier_id`, which is the number of qualifier edges.

In [13]:
kgtk("""
    query -i all
        --match '
            (n1)-[id]->(n2),
            (id)-[qualifier_id]->(qualifier_value)'
        --return 'count(distinct qualifier_id)'
""")

   count(DISTINCT graph_9_c2."id")
0                           455226

We can enhance the query to show us the distribution of properties used as qualifiers by introducing a variable `qualifier_property` to capture the property:

In [14]:
%%time
kgtk("""
    query -i all
        --match '
            (n1)-[id]->(n2),
            (id)-[qualifier_id {label: qualifier_property}]->(qualifier_value)'
        --return 'qualifier_property as node1, "count" as label, count(distinct qualifier_id) as node2'
        --order-by 'cast(node2, int) desc'
    / add-labels
""")

CPU times: user 11.2 ms, sys: 19.1 ms, total: 30.3 ms
Wall time: 6.62 s

     node1  label   node2                   node1;label
0    P1545  count  134301           'series ordinal'@en
1     P585  count   96781            'point in time'@en
2     P580  count   33212               'start time'@en
3     P459  count   32944     'determination method'@en
4     P805  count   19969  'statement is subject of'@en
..     ...    ...     ...                           ...
719   P945  count       1               'allegiance'@en
720   P952  count       1  'ISCO-88 occupation code'@en
721    P97  count       1              'noble title'@en
722   P974  count       1                'tributary'@en
723   P991  count       1     'successful candidate'@en

[724 rows x 4 columns]

## Get instance counts for each class

In this part you will do the simplest profiling query where you count the number of direct instancess of each class.
We can compute the instance counts by retrieving all statements that use `instance of (P31)` and counting the instances for each class.
We order the result by the number of instances to see the classes that have the most instances.
You can see that our tutorial KG contains a large number of people, and that there is a long tail of classes with very few instances; this is common in Wikidata, which defines over 1 million classes.

In [15]:
%%time
kgtk("""
    query -i all
        --match '(instance)-[:P31]->(class)'
        --return 'class as class, count(distinct instance) as count'
        --order-by 'cast(count, int) desc' 
    / add-labels
""")

CPU times: user 36 ms, sys: 21.9 ms, total: 57.9 ms
Wall time: 2.27 s

           class  count                            class;label
0             Q5  13873                             'human'@en
1      Q15221623   3177                'bilateral relation'@en
2         Q11424   2136                              'film'@en
3          Q4022   1550                             'river'@en
4          Q3918    815                        'university'@en
...          ...    ...                                    ...
5779  Q100509052      1               'metallurgical plant'@en
5780    Q1004887      1                      'thermal bath'@en
5781    Q1002812      1              'metropolitan borough'@en
5782  Q100212002      1                'subjective quality'@en
5783  Q100039327      1  'autonomous constitutional agency'@en

[5784 rows x 3 columns]

We want to add the profiling data back into the KG so that we can use it in queries and look at it in the browser.
To do so, we create a KGTK graph by using `node1, label, node2` as column headers:

In [16]:
%%time
kgtk("""
    query -i all
        --match '(instance)-[:P31]->(class)'
        --return 'class as node1, "P31_count" as label, count(distinct instance) as node2'
        --order-by 'cast(node2, int) desc'
    --limit 10 
""")

CPU times: user 6.15 ms, sys: 15.6 ms, total: 21.7 ms
Wall time: 1.08 s

       node1      label  node2
0         Q5  P31_count  13873
1  Q15221623  P31_count   3177
2     Q11424  P31_count   2136
3      Q4022  P31_count   1550
4      Q3918  P31_count    815
5   Q4164871  P31_count    645
6   Q1549591  P31_count    627
7   Q3917681  P31_count    614
8  Q19595382  P31_count    595
9  Q11862829  P31_count    568

It is good practice to add identifiers to the edges so that we can add qualifiers later if we desire. To add the identifiers, we chain the query output to the `add-id` command:

In [17]:
%%time
kgtk("""
    query -i all
        --match '(instance)-[:P31]->(class)'
        --return 'class as node1, "P31count" as label, count(distinct instance) as node2'
        --order-by 'cast(node2, int) desc' 
    / add-id --id-style wikidata
""")

CPU times: user 63 ms, sys: 29.1 ms, total: 92.1 ms
Wall time: 1.98 s

          node1     label  node2                         id
0            Q5  P31count  13873         Q5-P31count-247e30
1     Q15221623  P31count   3177  Q15221623-P31count-61d8c4
2        Q11424  P31count   2136     Q11424-P31count-907bdc
3         Q4022  P31count   1550      Q4022-P31count-c27484
4         Q3918  P31count    815      Q3918-P31count-96da2f
...         ...       ...    ...                        ...
5779    Q995347  P31count      1    Q995347-P31count-6b86b2
5780  Q99566538  P31count      1  Q99566538-P31count-6b86b2
5781    Q996839  P31count      1    Q996839-P31count-6b86b2
5782  Q99960791  P31count      1  Q99960791-P31count-6b86b2
5783  Q99972219  P31count      1  Q99972219-P31count-6b86b2

[5784 rows x 4 columns]

Now that we saw the steps to create the graph with the counts, we want to output the results to a file using the `-o` option:

In [18]:
%%time
kgtk("""
    query -i all
        --match '(instance)-[:P31]->(class)'
        --return 'class as node1, "P31count" as label, count(distinct instance) as node2'
        --order-by 'cast(node2, int) desc'
    / add-id --id-style wikidata
    -o $OUT/metadata.p31.count.tsv
""")

CPU times: user 3.79 ms, sys: 13.9 ms, total: 17.7 ms
Wall time: 1.94 s

Confirm that the output file went to the right place:

In [19]:
!ls -l $OUT

total 5952
-rw-r--r--  1 amandeep  wheel  2171415 Mar 22 14:04 P39_P106.tsv
-rw-r--r--  1 amandeep  wheel   601680 Mar 22 14:04 metadata.p31.count.transitive.tsv
-rw-r--r--  1 amandeep  wheel   261137 Mar 22 14:12 metadata.p31.count.tsv
drwxr-xr-x  5 amandeep  wheel      160 Mar 22 14:12 temp.tutorial-profiling

Load the `P31count` graph in the KGTK cache so that we can use it in queries later

In [20]:
kgtk("""
    query -i $OUT/metadata.p31.count.tsv --as p31count --limit 2
""")

       node1     label  node2                         id
0         Q5  P31count  13873         Q5-P31count-247e30
1  Q15221623  P31count   3177  Q15221623-P31count-61d8c4

Summary of this section:
- In this section we computed the count of instances for every class in our KG.
- We illustrated the use of `instance of (P31)` to do queries.
- We illustrated common conventions to add identifiers to edges and to save results to files.

## Compute `P31count_transitive`, the count of instances of a class including the instances of all the subclasses

Approach:
- get the class of each instance
- get all the superclass of the class of each instance
- for every superclass, count all the instances

> This query will run at the scale of all Wikidata, which contains millions of classes

We add the labels to see the results, not surprisingly, `entity` has the most instances, and the top classes are those at the top of the Wikidata ontology:

In [21]:
%%time
kgtk("""
    query -i all
        --match '
            (instance)-[:P31]->(class),
            (class)-[:P279star]->(superclass)'
        --return 'superclass as class, count(distinct instance) as count'
        --order-by 'cast(count, int) desc'
    / add-labels
""")

CPU times: user 52.1 ms, sys: 29.7 ms, total: 81.8 ms
Wall time: 14.3 s

           class  count                            class;label
0         Q35120  58496                            'entity'@en
1      Q99527517  38373                 'collection entity'@en
2      Q28813620  35555                               'set'@en
3      Q16887380  35533                             'group'@en
4      Q58415929  30837            'spatio-temporal entity'@en
...          ...    ...                                    ...
8926  Q100166391      1          'salt production facility'@en
8927    Q1001059      1                              'writ'@en
8928    Q1000660      1              'algebra over a field'@en
8929  Q100052008      1       'anthropomorphic Pantherinae'@en
8930  Q100039327      1  'autonomous constitutional agency'@en

[8931 rows x 3 columns]

Store the results in a file using a new property `P31count_transitive`

In [22]:
%%time
kgtk("""
    query -i all 
        --match '
            (instance)-[:P31]->(class),
            (class)-[:P279star]->(superclass)'
        --return 'superclass as node1, "P31count_transitive" as label, count(distinct instance) as node2'
        --order-by 'cast(node2, int) desc'
    / add-id --id-style wikidata
    -o $OUT/metadata.p31.count.transitive.tsv
""")

CPU times: user 7.26 ms, sys: 15.8 ms, total: 23 ms
Wall time: 12.6 s

Find the number of instances of `Q5: human`, `artist: Q483501` and `film director: Q2526255`. There are many instances of human, but only one of artist and zero of film director.

In [23]:
kgtk("""
    filter -i $OUT/metadata.p31.count.transitive.tsv -p "Q5, Q483501, Q2526255 ;;" / add-labels
""")

,node1,label,node2,id,node1;label
0,Q5,P31count_transitive,13944,Q5-P31count_transitive-c2d55f,'human'@en
1,Q483501,P31count_transitive,1,Q483501-P31count_transitive-6b86b2,'artist'@en

The reason there are no instances of `artist: Q483501` or `film director: Q2526255`  is that Wikidata uses the property `occupation: P106` to relate people to their occupations, so the connection between human and artist of director is not `instance of: P31`. It would be nice if the browser page for `artist: Q483501` or `film director: Q2526255` would show the number of people with this occupation. DBpedia uses a different model where humans are instances of artist or film director.

### Summary of this section
In this section we:
- Computed the count of instaces of every class, including all subclasses.
- Introduced `P279star`, the precomputed transitive closure of the Wikidata `subclass of (P279)` property that allows you to conveniently do queries over all super classes or subclasses of an entity.

## Define `P31x`, a generalization of `instance of: P31`

In our KG we are going to define a new property called `instance of (generalized): P31x` that behaves like DBpedia, so that we can ask for instances of `artist: Q483501`.
We do this by generalizing `occupation: P106` abd `position held: 39` to also behave as `P31` statements.

Approach:
- Combine `x P31 y`, `x P106 y` and `x P39 y` statements using a new `P31x` predicate

Use the `filter` to take a peek at the data and see whether our plan makes sense.

In [24]:
!kgtk --debug filter -i $item -p "; P39, P106 ;" / add-labels / head

node1	label	node2	id	node2;wikidatatype	node1;label	label;label	node2;label
Q1000048	P106	Q1622272	Q1000048-P106-Q1622272-3a1be6b5-0	wikibase-item	'Franz Zimmermann'@en	'occupation'@en	'university teacher'@en
Q1000048	P106	Q16267607	Q1000048-P106-Q16267607-e13e45d1-0	wikibase-item	'Franz Zimmermann'@en	'occupation'@en	'classical philologist'@en
Q100063874	P39	Q1162163	Q100063874-P39-Q1162163-ae076e77-0	wikibase-item	'Catherine Musson'@en	'position held'@en	'director'@en
Q100066085	P39	Q1162163	Q100066085-P39-Q1162163-93ac33fd-0	wikibase-item	'Anne-Laurence Mennessier'@en	'position held'@en	'director'@en
Q1001	P106	Q11774202	Q1001-P106-Q11774202-45d8eb34-0	wikibase-item	'Mahatma Gandhi'@en	'occupation'@en	'essayist'@en
Q1001	P106	Q17351648	Q1001-P106-Q17351648-e64838e9-0	wikibase-item	'Mahatma Gandhi'@en	'occupation'@en	'newspaper editor'@en
Q1001	P106	Q1930187	Q1001-P106-Q1930187-6cf568db-0	wikibase-item	'Mahatma Gandhi'@en	'occupation'@en	'journalist'@en
Q1001	P106	Q4964182	Q1001-P106-Q4964182-a0867b04-0	wikibase-item	'Mahatma Gandhi'@en	'occupation'@en	'philosopher'@en
Q1001	P106	Q808967	Q1001-P106-Q808967-57fe7a7e-0	wikibase-item	'Mahatma Gandhi'@en	'occupation'@en	'barrister'@en
Q100159381	P106	Q37226	Q100159381-P106-Q37226-d95f0b81-0	wikibase-item	'Victor Cherner'@en	'occupation'@en	'teacher'@en
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

In [25]:
kgtk("""
    filter -i $item -p "; P39, P106 ;"
    / add-labels
    -o $OUT/P39_P106.tsv
""")

In [26]:
kgtk("""
    head -i $OUT/P39_P106.tsv
""")

,node1,label,node2,id,node2;wikidatatype,node1;label,label;label,node2;label
0,Q1000048,P106,Q1622272,Q1000048-P106-Q1622272-3a1be6b5-0,wikibase-item,'Franz Zimmermann'@en,'occupation'@en,'university teacher'@en
1,Q1000048,P106,Q16267607,Q1000048-P106-Q16267607-e13e45d1-0,wikibase-item,'Franz Zimmermann'@en,'occupation'@en,'classical philologist'@en
2,Q100063874,P39,Q1162163,Q100063874-P39-Q1162163-ae076e77-0,wikibase-item,'Catherine Musson'@en,'position held'@en,'director'@en
3,Q100066085,P39,Q1162163,Q100066085-P39-Q1162163-93ac33fd-0,wikibase-item,'Anne-Laurence Mennessier'@en,'position held'@en,'director'@en
4,Q1001,P106,Q11774202,Q1001-P106-Q11774202-45d8eb34-0,wikibase-item,'Mahatma Gandhi'@en,'occupation'@en,'essayist'@en
5,Q1001,P106,Q17351648,Q1001-P106-Q17351648-e64838e9-0,wikibase-item,'Mahatma Gandhi'@en,'occupation'@en,'newspaper editor'@en
6,Q1001,P106,Q1930187,Q1001-P106-Q1930187-6cf568db-0,wikibase-item,'Mahatma Gandhi'@en,'occupation'@en,'journalist'@en
7,Q1001,P106,Q4964182,Q1001-P106-Q4964182-a0867b04-0,wikibase-item,'Mahatma Gandhi'@en,'occupation'@en,'philosopher'@en
8,Q1001,P106,Q808967,Q1001-P106-Q808967-57fe7a7e-0,wikibase-item,'Mahatma Gandhi'@en,'occupation'@en,'barrister'@en
9,Q100159381,P106,Q37226,Q100159381-P106-Q37226-d95f0b81-0,wikibase-item,'Victor Cherner'@en,'occupation'@en,'teacher'@en

Select all the `P31`, `P39` and `P106` statements and rewrite them as `P31x` statements, and also make sure that we do this only for humans:

In [27]:
kgtk("""
    query -i all
        --match '
            (n1)-[:P31]->(:Q5),
            (n1)-[r {label: property}]->(n2)'
        --where 'property in ["P106", "P39", "P31"]'
        --return 'distinct n1 as node1, "P31x" as label, n2 as node2'
        --limit 10
    / add-labels
""")

,node1,label,node2,node1;label,node2;label
0,Q1000048,P31x,Q1622272,'Franz Zimmermann'@en,'university teacher'@en
1,Q1000048,P31x,Q16267607,'Franz Zimmermann'@en,'classical philologist'@en
2,Q1000048,P31x,Q5,'Franz Zimmermann'@en,'human'@en
3,Q1000061,P31x,Q5,'Valentyn Symonenko'@en,'human'@en
4,Q100063874,P31x,Q5,'Catherine Musson'@en,'human'@en
5,Q100063874,P31x,Q1162163,'Catherine Musson'@en,'director'@en
6,Q100066085,P31x,Q5,'Anne-Laurence Mennessier'@en,'human'@en
7,Q100066085,P31x,Q1162163,'Anne-Laurence Mennessier'@en,'director'@en
8,Q1001,P31x,Q11774202,'Mahatma Gandhi'@en,'essayist'@en
9,Q1001,P31x,Q17351648,'Mahatma Gandhi'@en,'newspaper editor'@en

The query needs to be more sophisticated, because the previous query adds the extended `instance of` only to humans. If we don't do this, fictional characters that have occupations end up below `human (Q5)` due to the way the Wikidata ontology is structured. The fix is 1) to concatenate (`cat`)the results of the previuos query with the original `instance of (P31)` graph, 2) replace (`replace-nodes`) property `P31` with `P31x`, and 3) to deduplicate (`compact`).
The resulting graph goes in file `derived.P31x.tsv`:

Create replacement mapping file that maps `P31` to `P31x`.

In [8]:
!echo -e "node1\tlabel\tnode2\nP31\tsame_as_property\tP31x" > $TEMP/replace-P31.tsv
!cat $TEMP/replace-P31.tsv

node1	label	node2
P31	same_as_property	P31x

In [9]:
%%time
kgtk("""
    query -i item
        --match '
            (n1)-[:P31]->(:Q5),
            (n1)-[r {label: property}]->(n2)'
        --where 'property in ["P106", "P39", "P31"]'
        --return 'distinct n1 as node1, "P31x" as label, n2 as node2'
    / cat -i - -i $p31
    / replace-nodes --mapping-file $TEMP/replace-P31.tsv
    / add-id --id-style wikidata --overwrite-id True
    / compact
    -o $OUT/derived.P31x.tsv
""")

CPU times: user 11.8 ms, sys: 10.7 ms, total: 22.5 ms
Wall time: 7.65 s

Load the `p31x` graph defining our generalized `instance of` property:

In [10]:
kgtk("""
    query -i $OUT/derived.P31x.tsv --as p31x --limit 2
""")

   node1 label      node2                    id
0    P10  P31x  Q18610173    P10-P31x-Q18610173
1  P1000  P31x  Q18608871  P1000-P31x-Q18608871

Now we can fix our `P31count_transitive` property to also include classes such as `film director (Q2526255)`. Use the new `P31x` graph to substitute `P31x` for `P31` in our query that computes the class counts:

In [11]:
%%time
kgtk("""
    query -i all -i p31x
        --match '
            p31x: (instance)-[:P31x]->(class),
            all: (class)-[:P279star]->(superclass)'
        --return 'superclass as node1, "P31xcount_transitive" as label, count(distinct instance) as node2'
        --order-by 'cast(node2, int) desc'
    / add-id --id-style wikidata
    -o $OUT/metadata.p31x.count.transitive.tsv
""")

CPU times: user 10 ms, sys: 18 ms, total: 28 ms
Wall time: 12.7 s

Redo our query to get the number of instances of `Q5: human`, `artist: Q483501` and `film director: Q2526255`.
Now we get more reasonable counts for artist and film directors:

In [12]:
kgtk("""
    filter -i $OUT/metadata.p31x.count.transitive.tsv -p "Q5, Q483501, Q2526255 ;;" / add-labels
""")

,node1,label,node2,id,node1;label
0,Q5,P31xcount_transitive,13944,Q5-P31xcount_transitive-c2d55f,'human'@en
1,Q483501,P31xcount_transitive,2576,Q483501-P31xcount_transitive-109833,'artist'@en
2,Q2526255,P31xcount_transitive,674,Q2526255-P31xcount_transitive-8ef532,'film director'@en

Find out the classes that appear in the new file that didn't appear in the old file. To do this we use the `ifnotexists` command that can be used to subtract the statements of one grpah from the statements from another graph.
> Some classes may appear in both graphs and have their counts updated (e.g., artists appeared with a count of 1 before):

In [32]:
kgtk("""
    ifnotexists -i $OUT/metadata.p31x.count.transitive.tsv
        --filter-on $OUT/metadata.p31.count.transitive.tsv
        --input-keys node1
        --filter-keys node1
    / add-labels
""")

,node1,label,node2,id,node1;label
0,Q713200,P31xcount_transitive,1912,Q713200-P31xcount_transitive-a991b8,'performing artist'@en
1,Q33999,P31xcount_transitive,1911,Q33999-P31xcount_transitive-dc4bc8,'actor'@en
2,Q15980804,P31xcount_transitive,1400,Q15980804-P31xcount_transitive-55fdec,'media professional'@en
3,Q2285706,P31xcount_transitive,1222,Q2285706-P31xcount_transitive-16a3e9,'head of government'@en
4,Q3282637,P31xcount_transitive,881,Q3282637-P31xcount_transitive-28096b,'film producer'@en
...,...,...,...,...,...
902,Q957729,P31xcount_transitive,1,Q957729-P31xcount_transitive-6b86b2,'photojournalist'@en
903,Q96172702,P31xcount_transitive,1,Q96172702-P31xcount_transitive-6b86b2,'Minister General of the Order of Franciscans'@en
904,Q978708,P31xcount_transitive,1,Q978708-P31xcount_transitive-6b86b2,'Prime Minister of East Timor'@en
905,Q98084799,P31xcount_transitive,1,Q98084799-P31xcount_transitive-6b86b2,'professional photographer'@en
906,Q994779,P31xcount_transitive,1,Q994779-P31xcount_transitive-6b86b2,'delegate'@en

### Summary of this section
In this section we:
- Computed  `P31x` representing our generalized instance of property. Results in `derived.P31x.tsv`.
- Computed `P31xcount_transitive` as a revision of `P31count_transitive` to also include counts via occupation and position held links. Results in `metadata.p31x.count.transitive.tsv`.
- Illustrated how to work with precomputed transitive closures (`P279star`), which enables KGTK to efficiently execute queries that otherwise would be very expensive

## Compute the number of times each property appears in a class

In this section we will compute the distribution of the use of properties in every class in th KG. 
We want to know the count of the different properties used in all instance of a class.
For example, if we look at `film (Q11424)` we want to see what properties are used to describe films, including all subclasses of film.

Computing this distirbution is challenging because as the query below shows, there are many classes in our KG:

In [33]:
kgtk("""
    query -i all --match '(entity)-[:P279]->(class)' --return 'count(distinct class) as `count of classes`'
""")

   count of classes
0              7483

Approach: we divide the task into two steps:
- For every entity, compute the set of properties used to describe it, and store this information in `item_properties.tsv`
- For every class, collect all the instances below it, and count the number of times each property appears in `item_properties.tsv`

The query for the first step is below. 
The first clause of the match clause gets the properties used in every instance of the KG.
I included a second clause to get the data type of the property, and used the `--where` clause to exlude properties with external identifiers, as there are so many of them, and for the tutorial we want the query to run faster.

In [34]:
%%time
kgtk("""
    query -i all
        --match '
            (entity)-[l {label: property}]->(),
            (property)-[:datatype]->(datatype)'
        --where 'datatype != "external-id"' 
        --return 'distinct entity as node1, "Phas_property" as label, property as node2'
    / add-labels
""")

CPU times: user 4.79 s, sys: 870 ms, total: 5.66 s
Wall time: 15.5 s

,node1,label,node2,node1;label,node2;label
0,P8874,Phas_property,P1001,'Hong Kong film rating'@en,'applies to jurisdiction'@en
1,Q1001543,Phas_property,P1001,"'Embassy of Finland, Budapest'@en",'applies to jurisdiction'@en
2,Q100325415,Phas_property,P1001,"'Embassy of Belarus, Budapest'@en",'applies to jurisdiction'@en
3,Q1005422,Phas_property,P1001,"'Federal Office of Bundeswehr Equipment, Infor...",'applies to jurisdiction'@en
4,Q1006360,Phas_property,P1001,'Bundesminister'@en,'applies to jurisdiction'@en
...,...,...,...,...,...
837038,Q7020999,Phas_property,P991,'2017 French presidential election'@en,'successful candidate'@en
837039,Q72251,Phas_property,P991,'1876 United States presidential election'@en,'successful candidate'@en
837040,Q72472,Phas_property,P991,'1892 United States presidential election'@en,'successful candidate'@en
837041,Q72835,Phas_property,P991,'1908 United States presidential election'@en,'successful candidate'@en
837042,P991-P1855-Q327959-2d857cd2-0,Phas_property,P991,NaN,'successful candidate'@en

The results look good, so we add the identifiers to the edges and store the results in `item_properties.tsv`.

In [35]:
%%time
kgtk("""
    query -i all
        --match '
            (property)-[:datatype]->(datatype), 
            (entity)-[l {label: property}]->()'
        --where 'datatype != "external-id"' 
        --return 'distinct entity as node1, "Phas_property" as label, property as node2'
    / add-id --id-style wikidata
    -o $TEMP/item_properties.tsv
""")

CPU times: user 5.33 ms, sys: 20.3 ms, total: 25.7 ms
Wall time: 7.53 s

In the second step, we use `P279star` to get all the superclasses of each entity, and then look up the entity in the `item_properties` graph to find the properties it uses.
We invent a new property called `P1963computed` to store the counts. Wikidata has a property `properties for this type (P1963)` where editors can manually specify the properties that should be used to describe the instance of a class. We are computing the properties bottom up from the data, so we call the property `P1963computed`.

In the return clause, we list `superclass`, and the value of the `property` variable ahead of the `count` clause to tell KGTK that we want to aggregate by superclass and property. We reuse the Wikidata `quantity (P1114)` to record the counts:

> This query is very expensive to run on the full Wikidata as it touches every entity in Wikidata, but it will complete after many hours.

In [36]:
%%time
kgtk("""
    query -i all -i p31x -i $TEMP/item_properties.tsv
        --match ' 
            p31x: (entity)-[]->(class), 
            all: (class)-[:P279star]->(superclass),
            item_properties: (entity)-[l]->(property)'
        --return 'distinct superclass as node1, "P1963computed" as label, property as node2, count(distinct l) as P1114' \
        --order-by 'cast(P1114, int) desc'
        --limit 100
    / add-labels
""")

CPU times: user 58.4 ms, sys: 54.5 ms, total: 113 ms
Wall time: 2min 10s

,node1,label,node2,P1114,node1;label,node2;label
0,Q35120,P1963computed,P31,57874,'entity'@en,'instance of'@en
1,Q99527517,P1963computed,P31,37827,'collection entity'@en,'instance of'@en
2,Q28813620,P1963computed,P31,35036,'set'@en,'instance of'@en
3,Q16887380,P1963computed,P31,35014,'group'@en,'instance of'@en
4,Q58415929,P1963computed,P31,32620,'spatio-temporal entity'@en,'instance of'@en
...,...,...,...,...,...,...
95,Q24229398,P1963computed,P17,10839,'agent'@en,'country'@en
96,Q43229,P1963computed,P17,10815,'organization'@en,'country'@en
97,Q58416391,P1963computed,P856,10631,'spatial entity'@en,'official website'@en
98,Q27096213,P1963computed,P856,10630,'geographic entity'@en,'official website'@en
99,Q17334923,P1963computed,P856,10601,'location'@en,'official website'@en

The results look good, so we store them in `derived.P1963computed.tsv`

In [37]:
%%time
kgtk("""
    query -i all -i p31x -i $TEMP/item_properties.tsv
        --match ' 
            p31x: (entity)-[]->(class), 
            all: (class)-[:P279star]->(superclass),
            item_properties: (entity)-[l]->(property)'
        --return 'distinct superclass as node1, "P1963computed" as label, property as node2, count(distinct l) as P1114' 
    / add-id --id-style wikidata
    / normalize --add-id True
    -o $OUT/derived.P1963computed.tsv
""")

CPU times: user 45.6 ms, sys: 45.2 ms, total: 90.8 ms
Wall time: 1min 47s

Add the new graph to the databse and define alias `p1963computed` for it.

In [38]:
kgtk("""
    query -i $OUT/derived.P1963computed.tsv --as p1963computed --limit 10
""")

,node1,label,node2,id
0,Q100039327,P1963computed,P159,Q100039327-P1963computed-P159
1,Q100039327-P1963computed-P159,P1114,1,Q100039327-P1963computed-P159-P1114-1-0000
2,Q100039327,P1963computed,P17,Q100039327-P1963computed-P17
3,Q100039327-P1963computed-P17,P1114,1,Q100039327-P1963computed-P17-P1114-1-0000
4,Q100039327,P1963computed,P1813,Q100039327-P1963computed-P1813
5,Q100039327-P1963computed-P1813,P1114,1,Q100039327-P1963computed-P1813-P1114-1-0000
6,Q100039327,P1963computed,P31,Q100039327-P1963computed-P31
7,Q100039327-P1963computed-P31,P1114,1,Q100039327-P1963computed-P31-P1114-1-0000
8,Q100039327,P1963computed,P373,Q100039327-P1963computed-P373
9,Q100039327-P1963computed-P373,P1114,1,Q100039327-P1963computed-P373-P1114-1-0000

Let' see the distribution of properties for `film (Q11424)`:
> You can try it for `film director (Q2526255)` or `entity (Q35120)`, which gives you the distribution of all properties in the KG:

In [39]:
%%time
kgtk("""
    query -i p1963computed
        --match '
            (class:Q11424)-[l:P1963computed]->(property),
            (l)-[:P1114]->(quantity)'
        --return 'distinct class as class, property as property, quantity as count'
        --order-by 'cast(count, int) desc'
    / add-labels
""")

CPU times: user 10.9 ms, sys: 25.5 ms, total: 36.4 ms
Wall time: 4.79 s

,class,property,count,class;label,property;label
0,Q11424,P31,2447,'film'@en,'instance of'@en
1,Q11424,P577,1402,'film'@en,'publication date'@en
2,Q11424,P495,1398,'film'@en,'country of origin'@en
3,Q11424,P1476,1381,'film'@en,'title'@en
4,Q11424,P364,1368,'film'@en,'original language of film or TV show'@en
...,...,...,...,...,...
94,Q11424,P6251,1,'film'@en,'catchphrase'@en
95,Q11424,P641,1,'film'@en,'sport'@en
96,Q11424,P767,1,'film'@en,'contributor to the creative work or subject'@en
97,Q11424,P8411,1,'film'@en,'set in environment'@en
98,Q11424,P941,1,'film'@en,'inspired by'@en

Store the resulting graph in `derived.Pproperty_domain.tsv` and define the alias `property_domain` for it in the database:

In [41]:
%%time
kgtk("""
    query -i p1963computed
        --match '
            (class)-[l:P1963computed]->(property),
            (l)-[:P1114]->(quantity)'
        --return 'distinct property as node1, "Pproperty_domain" as label, class as node2, quantity as P1114'
        --order-by 'property, cast(P1114, int) desc'
    / add-id --id-style wikidata
    / normalize --add-id True
    -o $OUT/derived.Pproperty_domain.tsv
""")

kgtk("query -i $OUT/derived.Pproperty_domain.tsv --as property_domain --limit 10")

CPU times: user 14.6 ms, sys: 40.4 ms, total: 55 ms
Wall time: 15.2 s

,node1,label,node2,id
0,P1001,Pproperty_domain,Q35120,P1001-Pproperty_domain-Q35120
1,P1001-Pproperty_domain-Q35120,P1114,2317,P1001-Pproperty_domain-Q35120-P1114-2317-0000
2,P1001,Pproperty_domain,Q99527517,P1001-Pproperty_domain-Q99527517
3,P1001-Pproperty_domain-Q99527517,P1114,1940,P1001-Pproperty_domain-Q99527517-P1114-1940-0000
4,P1001,Pproperty_domain,Q16889133,P1001-Pproperty_domain-Q16889133
5,P1001-Pproperty_domain-Q16889133,P1114,1866,P1001-Pproperty_domain-Q16889133-P1114-1866-0000
6,P1001,Pproperty_domain,Q16686448,P1001-Pproperty_domain-Q16686448
7,P1001-Pproperty_domain-Q16686448,P1114,1667,P1001-Pproperty_domain-Q16686448-P1114-1667-0000
8,P1001,Pproperty_domain,Q16887380,P1001-Pproperty_domain-Q16887380
9,P1001-Pproperty_domain-Q16887380,P1114,1410,P1001-Pproperty_domain-Q16887380-P1114-1410-0000

Let's see the distribution of classes for `cast member(P161)`. We restrict the results to be subclasses of `visual artwork (Q4502142)` because otherwise the results contain too many of the abstract classes. We see that property `cast member(P161)` is defined for film and subclasses of film:

In [42]:
kgtk("""
    query -i property_domain -i all
        --match '
            all: (class)-[:P279star]->(:Q4502142), 
            property_domain: (property:P161)-[l:Pproperty_domain]->(class),
            property_domain: (l)-[:P1114]->(quantity)'
        --return 'distinct property as node1, "Pproperty_domain" as label, class as node2, quantity as P1114'
        --order-by 'property, cast(P1114, int) desc'
        --limit 10
    / add-labels
""")

,node1,label,node2,P1114,node1;label,node2;label
0,P161,Pproperty_domain,Q11424,1133,'cast member'@en,'film'@en
1,P161,Pproperty_domain,Q4502142,1133,'cast member'@en,'visual artwork'@en
2,P161,Pproperty_domain,Q24869,38,'cast member'@en,'feature film'@en
3,P161,Pproperty_domain,Q229390,36,'cast member'@en,'3D film'@en
4,P161,Pproperty_domain,Q506240,17,'cast member'@en,'television film'@en
5,P161,Pproperty_domain,Q61283808,8,'cast member'@en,'Star Trek film'@en
6,P161,Pproperty_domain,Q202866,5,'cast member'@en,'animated film'@en
7,P161,Pproperty_domain,Q25110269,5,'cast member'@en,'live-action animated film'@en
8,P161,Pproperty_domain,Q517386,5,'cast member'@en,'live action'@en
9,P161,Pproperty_domain,Q24862,4,'cast member'@en,'short film'@en

### Summary of this section
In this section we:
- Computed  `P1963computed`, to record the frequence of the use of properties in every class.
- Used `P1963computed` to see the distribution of properties for a few classes.
- Illustrated the ability to break down very expensive queries into simpler steps.
- Illustrated a KGTK feature that allows you to use the results of one query as a new graph (`$TEMP/item_properties.tsv`) that can be integrated into other queries.

## Compute the distribution of units for quantity properties
This part of the tutorial illustrates how to work with KGTK structured literals:
- quantities: composed of a numeric value followed by the identifier of a unit, quantities can also define tolerances
- dates and times: composed of an ISO-formatted date, followed by a numeric precision indicator, and sometimes by a calendar
- monolingual strings: composed of a unicode string followed by a language tag

Additional documentation on the KGTK file format is in https://kgtk.readthedocs.io/en/latest/specification/
and documentation for the functions to operate on structured literals within queries is in https://kgtk.readthedocs.io/en/latest/transform/query/

Below is a specific example of how to query the units in structured literals. THe objective in the example is to compute a distribution of the units used in all properties that store quantities.
The query uses the `quantity` graph, which contains all properties whose values are quantities. 

The results of the query are interesting as we see some inconsistencies in the data present in our small subset of Wikidata. 
For example, most instances of `population (P1082)` have no units `point in time (Q186408)`, one has unit `Habitants (Q15621516)`, neither of which are units of `unit of measurement (Q47574)`

In [43]:
kgtk("""
    query -i quantity
        --match '(n1)-[l {label: property}]->(quantity)'
        --return 'distinct property as node1, "Pproperty_units_used" as label, kgtk_quantity_wd_units(quantity) as node2, count(distinct l) as P1114'
        --order-by 'property, cast(P1114, int) desc'
    / add-labels
""")

,node1,label,node2,P1114,node1;label,node2;label
0,P1081,Pproperty_units_used,NaN,6810,'Human Development Index'@en,NaN
1,P1082,Pproperty_units_used,NaN,46643,'population'@en,NaN
2,P1082,Pproperty_units_used,Q186408,2,'population'@en,'point in time'@en
3,P1082,Pproperty_units_used,Q15621516,1,'population'@en,'Habitants'@en
4,P1082,Pproperty_units_used,Q5727902,1,'population'@en,'circa'@en
...,...,...,...,...,...,...
418,P8476,Pproperty_units_used,NaN,992,'BTI Governance Index'@en,NaN
419,P8477,Pproperty_units_used,NaN,970,'BTI Status Index'@en,NaN
420,P8687,Pproperty_units_used,NaN,6469,'social media followers'@en,NaN
421,P8843,Pproperty_units_used,NaN,201,'poverty incidence'@en,NaN
422,P8887,Pproperty_units_used,Q712226,1,'water area'@en,'square kilometre'@en

We will store the units graph in `derived.Pproperty_units_used.tsv`. The final query includes a `where` clause to filter out the NULL values.

In [44]:
kgtk("""
    query -i quantity
        --match '(n1)-[l {label: property}]->(quantity)'
        --where 'kgtk_quantity_wd_units(quantity) IS NOT NULL'
        --return 'distinct property as node1, "Pproperty_units_used" as label, kgtk_quantity_wd_units(quantity) as node2, count(distinct l) as P1114'
        --order-by 'property, cast(P1114, int) desc'
    / add-id --id-style wikidata
    / normalize --add-id True
    -o $OUT/derived.Pproperty_units_used.tsv
""")

kgtk("query -i $OUT/derived.Pproperty_units_used.tsv --as property_units_used --limit 10")

,node1,label,node2,id
0,P1082,Pproperty_units_used,Q186408,P1082-Pproperty_units_used-Q186408
1,P1082-Pproperty_units_used-Q186408,P1114,2,P1082-Pproperty_units_used-Q186408-P1114-2-0000
2,P1082,Pproperty_units_used,Q15621516,P1082-Pproperty_units_used-Q15621516
3,P1082-Pproperty_units_used-Q15621516,P1114,1,P1082-Pproperty_units_used-Q15621516-P1114-1-0000
4,P1082,Pproperty_units_used,Q5727902,P1082-Pproperty_units_used-Q5727902
5,P1082-Pproperty_units_used-Q5727902,P1114,1,P1082-Pproperty_units_used-Q5727902-P1114-1-0000
6,P1083,Pproperty_units_used,Q44666669,P1083-Pproperty_units_used-Q44666669
7,P1083-Pproperty_units_used-Q44666669,P1114,2,P1083-Pproperty_units_used-Q44666669-P1114-2-0000
8,P1083,Pproperty_units_used,Q42177,P1083-Pproperty_units_used-Q42177
9,P1083-Pproperty_units_used-Q42177,P1114,1,P1083-Pproperty_units_used-Q42177-P1114-1-0000

### Summary of this section
In this section we:
- Computed the distribution of the units used for properties that store quantities
- Found examples of inappropriate use of units of measure in Wikidata
- Illustrated how to use functions in `query` to extract elements from structured literals

## Compute the number of awards by sex or gender of the receiver

First, get a distirbution of the `sex or gender (P21)` of people in our graph.
The distribution is skewed, perhaps because it is skewed in Wikidata or a result of how the tutorial graph was constructed.

In [45]:
kgtk("""
    query -i all
        --match '
            (person)-[:P31]->(:Q5),
            (person)-[:P21]->(sex_or_gender)'
        --return 'distinct sex_or_gender as sex_or_gender, count(distinct person) as count'
    / add-labels
""")

  sex_or_gender  count sex_or_gender;label
0      Q6581072   1783         'female'@en
1      Q6581097   8111           'male'@en

Below, we compute the distirbution of `sex or gender (P21)`  per type of award. We use the property `award received (P166)` to extract the awards that people received.

We create a new property `Paward_count` to record the count, and put the `sex or gender (P21)` as a qualifier.

In [46]:
%%time
kgtk("""
    query -i all
        --match '
            (actor)-[:P31]->(:Q5),
            (actor)-[:P21]->(sex_or_gender),
            (actor)-[:P166]->(award)-[:P31]->(award_type)'
        --return 'distinct award_type as node1, "Paward_count" as label, sex_or_gender as P21, count(distinct actor) as node2'
        --order-by 'award_type'
    / add-labels
""")

CPU times: user 8.96 ms, sys: 21.5 ms, total: 30.4 ms
Wall time: 3.35 s

,node1,label,P21,node2,node1;label,P21;label
0,Q101007233,Paward_count,Q6581097,1,'film critics association'@en,'male'@en
1,Q1011547,Paward_count,Q6581072,38,'Golden Globe Award'@en,'female'@en
2,Q1011547,Paward_count,Q6581097,42,'Golden Globe Award'@en,'male'@en
3,Q101251494,Paward_count,Q6581097,24,'star'@en,'male'@en
4,Q1044427,Paward_count,Q6581072,8,'Primetime Emmy Award'@en,'female'@en
...,...,...,...,...,...,...
220,Q96474707,Paward_count,Q6581097,16,'honorary award'@en,'male'@en
221,Q96474709,Paward_count,Q6581072,2,'award for best visual effects'@en,'female'@en
222,Q96474709,Paward_count,Q6581097,121,'award for best visual effects'@en,'male'@en
223,Q973011,Paward_count,Q6581097,18,'campaign medal'@en,'male'@en
224,Q97551638,Paward_count,Q6581097,2,'merit order'@en,'male'@en

Store the new `Paward_count` graph in a file and define the alias `award_count` for it

In [47]:
%%time
kgtk("""
    query -i all
        --match '
            (actor)-[:P31]->(:Q5),
            (actor)-[:P21]->(sex_or_gender),
            (actor)-[:P166]->(award)-[:P31]->(award_type)'
        --return 'distinct award_type as node1, "Paward_count" as label, sex_or_gender as P21, count(distinct actor) as node2'
        --order-by 'award_type'
    / add-id --id-style wikidata
    / normalize --add-id True
    -o $OUT/derived.Paward_count.tsv
""")

kgtk("query -i $OUT/derived.Paward_count.tsv --as award_count --limit 10")

CPU times: user 10.6 ms, sys: 35.9 ms, total: 46.4 ms
Wall time: 4.35 s

,node1,label,node2,id
0,Q101007233,Paward_count,1,Q101007233-Paward_count-6b86b2
1,Q101007233-Paward_count-6b86b2,P21,Q6581097,Q101007233-Paward_count-6b86b2-P21-Q6581097-0000
2,Q1011547,Paward_count,38,Q1011547-Paward_count-aea921
3,Q1011547-Paward_count-aea921,P21,Q6581072,Q1011547-Paward_count-aea921-P21-Q6581072-0000
4,Q1011547,Paward_count,42,Q1011547-Paward_count-73475c
5,Q1011547-Paward_count-73475c,P21,Q6581097,Q1011547-Paward_count-73475c-P21-Q6581097-0000
6,Q101251494,Paward_count,24,Q101251494-Paward_count-c23560
7,Q101251494-Paward_count-c23560,P21,Q6581097,Q101251494-Paward_count-c23560-P21-Q6581097-0000
8,Q1044427,Paward_count,8,Q1044427-Paward_count-2c6242
9,Q1044427-Paward_count-2c6242,P21,Q6581072,Q1044427-Paward_count-2c6242-P21-Q6581072-0000

### Summary of this section
In this section we:
- Profiled awards to find the gender or sex of awardees, and found that males appear more frequently. We don't know if it is a skew in Wikidata or the real world.
- Defined a new property to hold the data so that it can be shown in the browser.

In [48]:
kgtk("""
    query -i all
        --match '
            (award)-[P31]->(award_type)-[:P279star]->(:Q4220917)'
        --return 'distinct award_type as award_type'
    / add-labels
""")

   award_type                                 award_type;label
0    Q1011547                          'Golden Globe Award'@en
1     Q106301   'Academy Award for Best Supporting Actress'@en
2     Q110145                            'MTV Movie Awards'@en
3    Q1111310            'Directors Guild of America Award'@en
4    Q1131772  'Saturn Award for Best Science Fiction Film'@en
..        ...                                              ...
90  Q96474700                   'award for best screenplay'@en
91  Q96474701           'award for best adapted screenplay'@en
92  Q96474704      'award for best makeup and hairdressing'@en
93  Q96474707                              'honorary award'@en
94  Q96474709               'award for best visual effects'@en

[95 rows x 2 columns]

# Deploy the results (optional)

**DO NOT RUN THE CELLS BELOW, IF YOU ARE RUNNING in Google Colab**

Deploy the tutorial KG after profiling so that the profiles can be used in other notebooks.

In [ ]:
files_to_deploy = [
    "metadata.p31x.count.transitive.tsv",
    "derived.P31x.tsv",
    "derived.P1963computed.tsv",
    "derived.Pproperty_domain.tsv",
    "derived.Punits_used.tsv",
    "derived.Paward_count.tsv"
]

# First copy all the files from the add-derived-graphs, we will overwrite the ones that change, e.g., all.tsv
!cp -p {tutorial_deployment_path + "/arnold"}/*.tsv* {project_deployment_path}

for file in files_to_deploy:
    path = "$OUT/" + file
    !cp -p {path} {project_deployment_path} 

all_file_path = project_deployment_path + "/all.tsv.gz"
if os.path.exists(all_file_path):
    !rm {all_file_path}
!kgtk cat -i {tutorial_deployment_path + "/arnold/all.tsv.gz"} -i {project_deployment_path}/*.tsv -o {all_file_path}

List all the files:

In [ ]:
!ls -l {project_deployment_path}